In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import os
from util import HISTORICAL_FILE_SAMPLE

In [2]:
df2 = pd.read_excel("historical_sample_join.xlsx", keep_default_na=False)
#reads projects from Excel file

len(df2)
df2

,Unnamed: 0,PROJECTS,COMMITS,PostGIS,Snowflake,RiakKV,Informix,PostgreSQL,GoogleBigQuery,H2,...,Hazelcast,Teradata,Elasticsearch,Redis,Join_Ignite_Sql,Join_Ignite_NoSql,Join_MarkLogic_Sql,Join_MarkLogic_NoSql,Join_Virtuoso_Sql,Join_Virtuoso_NoSql
0,0,Activiti,1,0,0,0,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
1,1,Activiti,2,0,0,0,0,1,0,1,...,0,0,0,0,1,0,0,0,0,0
2,2,Activiti,3,0,0,0,0,1,0,1,...,0,0,0,0,1,1,0,0,0,0
3,3,Activiti,4,0,0,0,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
4,4,Activiti,5,0,0,0,0,1,0,1,...,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,115,zaproxy,6,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
116,116,zaproxy,7,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
117,117,zaproxy,8,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
118,118,zaproxy,9,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
119,119,zaproxy,10,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [3]:
df2.drop(['Unnamed: 0'], axis=1, inplace=True)
df2

,PROJECTS,COMMITS,PostGIS,Snowflake,RiakKV,Informix,PostgreSQL,GoogleBigQuery,H2,SapAdaptiveServer,...,Hazelcast,Teradata,Elasticsearch,Redis,Join_Ignite_Sql,Join_Ignite_NoSql,Join_MarkLogic_Sql,Join_MarkLogic_NoSql,Join_Virtuoso_Sql,Join_Virtuoso_NoSql
0,Activiti,1,0,0,0,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1,Activiti,2,0,0,0,0,1,0,1,0,...,0,0,0,0,1,0,0,0,0,0
2,Activiti,3,0,0,0,0,1,0,1,0,...,0,0,0,0,1,1,0,0,0,0
3,Activiti,4,0,0,0,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
4,Activiti,5,0,0,0,0,1,0,1,0,...,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,zaproxy,6,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
116,zaproxy,7,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
117,zaproxy,8,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
118,zaproxy,9,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
119,zaproxy,10,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [52]:
df2 = pd.read_excel("spmf_teste.xlsx", keep_default_na=False)
len(df2)
df2

    PROJECTS  COMMITS  MySQL  PTSQL  H2  Oracle
0   Activiti        1      1      0   0       0
1   Activiti        2      1      1   1       0
2   Activiti        3      1      1   1       1
3   Activiti        4      1      1   0       0
4        Che        1      1      0   0       0
5        Che        2      0      0   1       0
6        Che        3      0      1   1       0
7        Che        4      1      0   1       0
8   Pinpoint        1      1      1   0       0
9   Pinpoint        2      0      0   1       1
10  Pinpoint        3      0      0   0       1
11  Pinpoint        4      0      1   1       0

In [53]:
dict_col=[]
#for row in df2.itertuples():
    #print(row.index()) 
    #print((col)
linha=[]
for col in df2.columns:
    #linha=[]
    if df2.columns.get_loc(col) == 0:
        linha.append('@CONVERTED_FROM_TEXT')
    elif df2.columns.get_loc(col) > 1: #@ITEM=1=apple
        #linha=[]
        linha.append('@ITEM='+ str(df2.columns.get_loc(col)*1000)+ '=IN' + col)
        linha.append('@ITEM='+ str(df2.columns.get_loc(col))+ '=' + col)
        #dict_col.append(linha)
        #linha=[]
        linha.append('@ITEM='+ str(df2.columns.get_loc(col)*100)+ '=OUT' + col)
        
linha.append('@ITEM=-1=|')
dict_col.append(linha)
print(dict_col)

[['@CONVERTED_FROM_TEXT', '@ITEM=2000=INMySQL', '@ITEM=2=MySQL', '@ITEM=200=OUTMySQL', '@ITEM=3000=INPTSQL', '@ITEM=3=PTSQL', '@ITEM=300=OUTPTSQL', '@ITEM=4000=INH2', '@ITEM=4=H2', '@ITEM=400=OUTH2', '@ITEM=5000=INOracle', '@ITEM=5=Oracle', '@ITEM=500=OUTOracle', '@ITEM=-1=|']]

In [54]:
def verify_BD (db, list):
    try:
        BD = list.index(db)
    except:
        BD = -1
    return BD

In [55]:
def separate_list(list):
    list1=[]
    list2=[]
    start = 0
    limit_pos =[]
    final = len(list)
    #print(final)
    
    for i,l in enumerate (list):
        if l == '-1':
            limit_pos.append(i)
        #print(limit_pos)
        
    # list = lista.reverse
    # print (list)
    if final > 0 and len(limit_pos) > 0:
        for j,p in enumerate (limit_pos[::-1]): #[::-1]
            if len(limit_pos) == 1 and final > p:
                 list1 = list[:p]
                 list2 = list[p+1:]
            elif len(limit_pos) <= 2 and (list[final-1] == '-1' or list[final-1] == '-1 -2') :
                start = limit_pos[j-2]
                list1 = list[start+1:p]
                if list[final-1] == '-1 -2':
                    list2 = list[p+1:j-1]  
                else:                     
                    list2 = list[p+1:]           
                #print('entrou no 1',  j, p, start, j-1, j-2)
                break#return list1,list2   
            else:
                start = limit_pos[j-2]
                list1 = list[start+1:p]  
                if list[final-1] == '-1 -2':
                    #print('entrou no 1 do else', j, p, start, j-1, list[67], final)
                    list2 = list[p+1:j-1]
                else: 
                    #print('entrou no 2', j, p, start, j-1, list[67], final)                    
                    list2 = list[p+1:]
                #print('entrou no 2', j, p, start, j-1, list[67], final)
                break
    else:
        list1 = ['-1']
        list2 = list.copy()
    return list1 , list2
linha = [6000,3000,40,50,'-1']
#'-1', 6, 8, 32, 36, 49000, '-1',6, 8, 32, 36, 49, 50000, 6, 8, 32, 36, 49, 50000, '-1', 6, 8, 32, 36, 4900, 5000, '-1', 6, 8, 32, 36, 49000, '-1', 6, 8, 32, 36, 4900, '-1', 6, 8, 32, 36, 4900, 50000, '-1', 6, 8, 32, 36, 49000, '-1', 6, 8, 32, 36, 4900, '-1', 6, 8, 32, 36, 5400, '-1 -2'] 
print(separate_list(linha))
line1,line2 = separate_list(linha)
print(line1)
print(line2)

([6000, 3000, 40, 50], [])
[6000, 3000, 40, 50]
[]

30
12
[[6000, 8000, 32000, 36000, '-1', 6, 8, 32, 36, 49000, '-1', 6, 8, 32, 36, 49, 50000, '-1', 6, 8, 32, 36, 4900, 5000, '-1', 6, 8, 32, 36, 49000, '-1', 6, 8, 32, 36, 4900, '-1', 6, 8, 32, 36, 4900, 50000, '-1', 6, 8, 32, 36, 49000, '-1', 6, 8, 32, 36, 4900, '-1', 6, 8, 32, 36, 4900, '-1 -2'], [12000, 24000, 27000, 34000, 36000, 38000, 41000, 43000, '-1', 12, 24, 27, 34, 36, 38, 41, 43, '-1', 12, 24, 27, 34, 36, 38, 41, 43, '-1', 12, 24, 27, 34, 36, 38, 41, 43, '-1', 12, 24, 27, 34, 36, 38, 41, 43, '-1', 12, 24, 27, 34, 36, 38, 41, 43, '-1', 12, 24, 27, 34, 36, 38, 41, 43, '-1', 12, 24, 27, 34, 36, 38, 41, 43, '-1', 12, 24, 27, 34, 36, 38, 41, 43, '-1', 12, 24, 27, 34, 36, 38, 41, 43, '-1 -2'], [6000, 8000, 9000, 14000, 18000, 24000, 26000, 27000, 28000, 31000, 32000, 33000, 36000, 37000, 41000, 43000, 47000, 48000, '-1', 6, 8, 9, 14, 18, 24, 26, 27, 28, 31, 32, 33, 36, 37, 41, 43, 47, 48, '-1', 6, 8, 9, 14, 18, 24, 26, 27, 28, 31, 32, 33, 36, 37, 41, 43, 47, 48, '-1', 6, 8, 9, 14, 18, 24, 26, 27, 28, 31, 32, 33, 36, 37, 41, 43, 47, 48, '-1', 6, 8, 9, 14, 18, 24, 26, 27, 28, 31, 32, 33, 36, 37, 41, 43, 47, 48, 52000, '-1', 6, 8, 9, 14, 18, 24, 26, 27, 28, 31, 32, 33, 36, 37, 41, 43, 47, 48, 52, '-1', 6, 8, 9, 14, 18, 24, 26, 27, 28, 31, 32, 33, 36, 37, 41, 43, 47, 48, 52, '-1', 6, 8, 9, 14, 18, 24, 26, 27, 28, 31, 32, 33, 36, 37, 41, 43, 47, 48, 5200, '-1', 6, 8, 9, 14, 18, 24, 26, 27, 28, 31, 32, 33, 36, 37, 41, 43, 47, 48, 5200, '-1', 6, 8, 9, 14, 18, 24, 26, 27, 28, 31, 32, 33, 36, 37, 41, 43, 47, 48, 5200, '-1 -2'], [14000, 24000, 27000, 28000, 33000, 34000, 36000, 37000, 47000, 48000, 53000, '-1', 14, 24, 27, 28, 33, 34, 36, 37, 47, 48, 53, '-1', 14, 24, 27, 28, 33, 34, 36, 37, 47, 48, 5300, '-1', 14, 24, 27, 28, 33, 34, 36, 37, 47, 48, 53000, '-1', 14, 24, 27, 28, 33, 34, 36, 37, 47, 48, 5300, '-1', 14, 24, 27, 28, 33, 34, 36, 37, 47, 48, 53000, '-1', 14, 24, 27, 28, 33, 34, 36, 37, 47, 48, 53000, '-1', 14, 24, 27, 28, 33, 34, 36, 37, 47, 48, 5300, '-1', 14, 24, 27, 28, 33, 34, 36, 37, 47, 48, 5300, '-1', 14, 24, 27, 28, 33, 34, 36, 37, 47, 48, 5300, '-1 -2'], [32000, '-1', 32, '-1', 32, '-1', 32, '-1', 32, '-1', 32, '-1', 32, '-1', 32, '-1', 32, '-1', 32, '-1 -2'], [12000, 34000, 48000, '-1', 12, 34, 48, '-1', 12, 34, 48, '-1', 12, 34, 48, '-1', 12, 34, 48, '-1', 12, 34, 48, '-1', 12, 34, 48, '-1', 12, 34, 48, '-1', 12, 34, 48, '-1', 12, 34, 48, '-1 -2'], [6000, 8000, 9000, 28000, 32000, 36000, 41000, 47000, 48000, '-1', 6, 8, 9, 28, 32, 36, 41, 47, 48, '-1', 6, 8, 9, 28, 32, 36, 41, 47, 48, '-1', 6, 8, 9, 28, 32, 36, 41, 47, 48, '-1', 6, 8, 9, 28, 32, 36, 41, 47, 48, '-1', 6, 8, 9, 28, 32, 36, 41, 47, 48, '-1', 6, 8, 9, 28, 32, 36, 41, 47, 48, '-1', 6, 8, 9, 28, 32, 36, 41, 47, 48, '-1', 6, 8, 9, 28, 32, 36, 41, 47, 48, '-1', 6, 8, 9, 28, 32, 36, 41, 47, 48, '-1 -2'], [10000, '-1', 10, '-1', 10, '-1', 10, '-1', 10, '-1', 10, '-1', 10, '-1', 10, '-1', 10, '-1', 10, '-1 -2'], [9000, 18000, 36000, 43000, '-1', 24000, 27000, 3600, 900, 1800, 41000, 4300, '-1', 18000, 2400, 27, 32000, 36000, 41, 43000, '-1', 9000, 18000, 24000, 27, 32, 36000, 41, '-1', 9000, 18000, 24000, 27, 32, 36000, 41, 48000, '-1', 9000, 18000, 24000, 27, 32, 36000, 41, 48, '-1', 6000, 9000, 18000, 24000, 26000, 27, 32, 33000, 36000, 37000, 41, 48, '-1', 6, 9000, 18000, 24000, 26, 27, 32, 33, 36000, 37, 41, 48, '-1', 6, 9000, 18000, 24000, 26, 27, 28000, 32, 33, 36000, 37, 41, 48, '-1', 5000, 6, 9000, 18000, 24000, 26, 27, 28, 32, 33, 36000, 37, 41, 43000, 47000, 48, '-1 -2'], [32000, '-1', 32, '-1', 32, '-1', 32, '-1', 32, '-1', 32, '-1', 32, '-1', 32, '-1', 32, '-1', 32, '-1 -2'], [10000, 36000, '-1', 10, 36, '-1', 10, 36, '-1', 10, 36, '-1', 10, 36, '-1', 10, 36, '-1', 10, 36, '-1', 10, 36, '-1', 10, 36, '-1', 10, 36, '-1 -2']]

VersÃ£o final!!!! Funcionando GlÃ³ria a Deuuussss!!!!

In [56]:
coluna=[]

proj = 0
projant = 'xxxx'
commitant = 0
linha=[]
linhaant = []
contproj = 0
noBD = -2
noBDant = -2
for row in df2.itertuples():
    #print(row.Index) 
    #print((col)
    commitant = 0
    for col in df2.columns:
        if col == "PROJECTS":
            #proj = proj + 1
            #linha.append(getattr(row, col))
            #print(getattr(row, col))
            projatual = getattr(row, col)
            #print('atual novo:', projatual, 'anterior:', projant)
            
        elif col == "COMMITS":
            commitatual = getattr(row, col)
            #commitant = commitatual
            #linha.append(getattr(row, col))
            #print('Commit:',getattr(row, col))
        elif projatual == projant or row.Index == 0:# projant == 'xxxx':
            if (commitatual == commitant) :
                if (getattr(row, col) == 1):
                    line1 = []
                    line2 = []                   
                    line1,line2 = separate_list(linha)
                    #print(linha,line1,line2)
                    if len(line1)!= 0 and len(line2) > len(line1):# >=
                        inBD = verify_BD(df2.columns.get_loc(col)*1000,line2)
                        BD = verify_BD(df2.columns.get_loc(col),line2)
                        outBD= verify_BD(df2.columns.get_loc(col)*100,line2)
                        if inBD < 0 and BD < 0 and outBD < 0:
                            inBD = verify_BD(df2.columns.get_loc(col)*1000,line1)
                            BD = verify_BD(df2.columns.get_loc(col),line1)
                            outBD= verify_BD(df2.columns.get_loc(col)*100,line1)
                    #elif (inBD < 0 and BD < 0 and outBD < 0) or  (len(line1) >= len(line2)):
                    else:
                        inBD = verify_BD(df2.columns.get_loc(col)*1000,line1)
                        BD = verify_BD(df2.columns.get_loc(col),line1)
                        outBD= verify_BD(df2.columns.get_loc(col)*100,line1)

                    #inBD = verify_BD(df2.columns.get_loc(col)*1000,linha)
                    #outBD= verify_BD(df2.columns.get_loc(col)*100,linha)
                    #try:
                            #inBD = linha.index(df2.columns.get_loc(col)*1000)
                            
                            #BD = linha.index(df2.columns.get_loc(col))
                    #except:
                            #inBD = -1
                            #BD = -1
                    #print('Entrou if 1 commits iguais',linha, inBD, df2.columns.get_loc(col)*1000)
                    #if outBD >=0 or (BD < 0 and inBD < 0):
                    if (outBD >=0) or (BD < 0 and inBD < 0):
                    #if inBD < 0 or (inBD >= 0 and outBD >= 0): #and BD < 0:
                        #print('Entrou2:',linha, inBD, df2.columns.get_loc(col)*1000)
                        linha.append(df2.columns.get_loc(col)*1000)
                        linhaant.append(df2.columns.get_loc(col)*1000)#inclui agora
                        print('Entrou1:',inBD, BD, outBD, df2.columns.get_loc(col), line1, line2)# linha)
                    #elif BD >= 0 or inBD >= 0:
                    #BD >= 0 or (inBD >= 0 and outBD < 0): #and row.index == 0: if inBD >= 0 or (BD >= 0 and inBD < 0):
                    else:
                        #linha.append('No'+col)
                        #linha.append(-df2.columns.get_loc(col))
                        #print('Entrou1:',linha, inBD, df2.columns.get_loc(col)*1000)
                        linha.append(df2.columns.get_loc(col))
                        linhaant.append(df2.columns.get_loc(col))      
                        print('Entrou2:',inBD, BD,outBD, df2.columns.get_loc(col), line1, line2)#,linha)
                

                    #print('projs iguais e commits iguais','atual:', projatual,'anterior:', projant, commitatual, commitant, row.Index)
                    #print(df2[x])
                    #print('Database:', col)
                    #linha.append(col)
                    #linha.append(df2.columns.get_loc(col))
                    #linhaant.append(col)
                    #linhaant.append(df2.columns.get_loc(col))
                    #print('entrou commits')
                    commitant = commitatual
                elif getattr(row, col) == 0:
                    #Se for a primeira coluna e a linhaant tinha BD
                    if len(linha) == 0 and len(linhaant) != 0:
                        #print("Se primeira coluna",len(linha),len(linhaant))
                        inBD = verify_BD(df2.columns.get_loc(col)*1000, linha)
                        BD = verify_BD(df2.columns.get_loc(col), linha)
                        outBD =  verify_BD(df2.columns.get_loc(col)*100, linha)
                        #print("Entrou bd1",linha, df2.columns.get_loc(col),noBD)
                        #try:
                            #noBD = linhaant.index(col)
                            #noBD = linhaant.index(df2.columns.get_loc(col))
                        #except:
                            #   noBD = -1
                        #if outBD >= 0: #and row.index == 0:
                        if BD >= 0 or (inBD >= 0 and outBD < 0):
                            linha.append(df2.columns.get_loc(col)*100)
                            linhaant.append(df2.columns.get_loc(col)*100)#inclui agora
                            #falta apend na linha anterior
                        #print('primeira coluna',noBD, linha, col)
                        #print('entrou 1',noBD, noBDin, df2.columns.get_loc(col)*1000, linha,)
                        commitant = commitatual
                    elif len(linha) != 0 and len(linhaant) != 0:  
                        line1 = []
                        line2 = []                   
                        line1,line2 = separate_list(linha)
                        #print(linha,line1,line2)
                        if len(line1)!= 0:# and len(line2)!= 0:
                            inBD = verify_BD(df2.columns.get_loc(col)*1000, line1)
                            BD = verify_BD(df2.columns.get_loc(col), line1)
                            outBD =  verify_BD(df2.columns.get_loc(col)*100, line1)
                            #print("Entrou bd1",linha, line1 ,line2 , df2.columns.get_loc(col), BD, inBD, outBD)
                            #try:
                                #noBD = linhaant.index(col)
                                #noBD = linhaant.index(df2.columns.get_loc(col))
                            #except:
                                #   noBD = -1
                            #if outBD >= 0: #and row.index == 0:
                            if BD >= 0 or (inBD >= 0 and outBD < 0):
                                linha.append(df2.columns.get_loc(col)*100)
                                linhaant.append(df2.columns.get_loc(col)*100)#inclui agora
                        #Comentado daqui em diante
                        #outBD =  verify_BD(df2.columns.get_loc(col), linha)
                        #print("Entrou bd1",linha, df2.columns.get_loc(col),noBD)
                        #if outBD < 0:
                            #Verficando se na linha tinha o BD*1000
                         #   outBD =  verify_BD(int(df2.columns.get_loc(col)*1000), linha)
                            #print("Entrou bd2",df2.columns.get_loc(col),noBD,linha)
                        #print('TambÃ©m entra aqui',noBD, df2.columns.get_loc(col), linha)
                        #if outBD >= 0:# or noBDm >=0:# and noBDin >=0: #and row.index == 0:
                         #   linha.append(df2.columns.get_loc(col)*100)
                          #  linhaant.append(df2.columns.get_loc(col)*100)#inclui agora
                            #print('entrou 2',noBD, noBDin, df2.columns.get_loc(col)*1000, linha)
                        commitant = commitatual   
            elif (commitatual != commitant):
                if getattr(row, col) == 1:
                    #print('projs iguais ecommits diferentes','atual:', projatual,'anterior:', projant, commitatual, commitant, row.Index )
                    if row.Index == 0 or len(linha) == 0:
                        inBD = verify_BD(df2.columns.get_loc(col)*1000,linha)
                        outBD= verify_BD(df2.columns.get_loc(col)*100,linha)
                        #try:
                         #   inBD =  linha.index(df2.columns.get_loc(col)*1000)
                            #BD = linha.index(df2.columns.get_loc(col))
                       # except:
                                #BD = -1
                        #        inBD = -1
                        #print('Entrou if 1 commit diferentes', inBD, df2.columns.get_loc(col), linha)
                        if inBD < 0 or outBD >=0:
                            linha.append(df2.columns.get_loc(col)*1000)
                            linhaant.append(df2.columns.get_loc(col)*1000)#inclui agora
                        else: 
                            linha.append(df2.columns.get_loc(col))
                            linhaant.append(df2.columns.get_loc(col))
                       
                    else:
                        line1 = []
                        line2 = []                   
                        line1,line2 = separate_list(linha)
                        #print(linha,line1,line2)
                        if len(line1)!= 0:# and len(line2)!= 0:
                            linha.append('-1')
                            #linha.append(col)
                            #linha.append(df2.columns.get_loc(col))
                            linhaant.append('-1')
                            #linhaant.append(col)
                            #linhaant.append(df2.columns.get_loc(col))
                            inBD = verify_BD(df2.columns.get_loc(col)*1000,line2)
                            BD = verify_BD(df2.columns.get_loc(col),line2)
                            outBD= verify_BD(df2.columns.get_loc(col)*100,line2)
                            #try:
                            #   inBD =  linha.index(df2.columns.get_loc(col)*1000)
                                #BD = linha.index(df2.columns.get_loc(col))
                            #except:
                                    #BD = -1
                                    #inBD = -1
                            #print('Entrou if 2 commit diferentes',inBD, outBD, BD, df2.columns.get_loc(col), line1, line2)
                            if outBD >=0 or (BD < 0 and inBD < 0):
                                linha.append(df2.columns.get_loc(col)*1000)
                                linhaant.append(df2.columns.get_loc(col)*1000)#inclui agora
                                #print('entrou inbd 1 < 0',inBD,df2.columns.get_loc(col),linha)
                                #print('Entrou if 1 commit diferentes',inBD, outBD, BD, df2.columns.get_loc(col), line1, line2)
                            else:#if inBD >= 0 or (BD >= 0 and inBD < 0): 
                                linha.append(df2.columns.get_loc(col))
                                linhaant.append(df2.columns.get_loc(col))
                                #print('Entrou if 2 commit diferentes',inBD, outBD, BD, df2.columns.get_loc(col), line1, line2)
                        
                    commitant = commitatual
                elif getattr(row, col) == 0:
                    list1 = []
                    list2 = []
                    count = 0
                    start = 0
                    delimant= 0
                    listaant = []
                    newList = []             
                    #if linha == linhaant and linha != 0:
                    for i,l in enumerate (linha):
                        if l == '-1' and count == 0:
                            list1 = linha[:i]
                            list2 = linha[i+1:]
                            delimant = i
                            count = count+1
                            #print('entrou no 1',linha, list1, list2, i, count)
                        elif l == '-1' and count > 0 :
                            start = i - delimant
                            list1 = linha[start:i]                            
                            list2 = linha[i+1:]
                            count = count + 1
                            delimant = i
                            #print('entrou no 2',linha, list1, list2, i, count)
                        #print(newList,list1,list2)
                        if len(list1)!=0 and len(list2)!=0 and (i == len(linha)-1):
                            delim ='-1'
                            if delim not in list1 and delim not in list2:
                                newList = [int (l) for l in list1 if l not in list2 ]
                                #print(newList,list1,list2)
                                if newList != 0:
                                    #newList = [int (i) *100 if i %1000 != 0 else int(i/1000) for i in newList] #[int(i) * 100 for i in lista1]
                                    for i,n in enumerate (newList):
                                        if  n % 1000 == 0:
                                            #print('Entrou 1 antes',newList[i],newList)
                                            if (n not in list2) and (int(n/1000) not in list2):
                                                newList[i] = int (n/1000)
                                            #elif n/1000 not in list2:
                                                #newList[i] = int (n/1000)
                                                #print('Entrou 1',newList[i],n,newList,list2)
                                        elif n % 100 == 0:
                                            #print('Entrou 2 antes',newList[i],newList)
                                            newList[i] = int(n/100)
                                            #print('Entrou 2',newList[i],newList)

                                    newList = [int (i) *100 if i %1000 != 0 else i/1000 for i in newList ] #[int(i) * 100 for i in lista1]
                                    #newList = [int (i) for i in newList if i %1000 != 0] 
                                    #print(linha, list1 , list2, i,count, len(list1),len(list2),newList)
                                    ##[int(i) * 100 for i in lista1]
                                    #newList = [int (i) *100 if (i%1000 == 0) else int(i*10) for i in list1]
                                    #print(linha, list1 , list2, i,count, len(list1),len(list2),newList)
                                #listaant = newList
                    if len(newList) != 0: #and list1 not in newList:# #and newList != listaant:
                        newList2 = [int (l) for l in newList  if l not in linha ] #if l*10 not in linha] # or l*100
                        #print(linha, list1, list2, i,count, len(list1),len(list2), newList, newList2)
                        #if newList2 == newList:
                        #lista = ''
                        #lista = str(newList2)
                        #print(linha,  newList, len(newList),len(newList2), newList2) 
                        pos = len(linha)-len(newList2) 
                        #linha.insert(pos,newList2)
                        for i,l in enumerate (newList2):
                            if i == 0 and linha[pos] != '-1':           
                                linha.insert(pos,l)
                                linhaant.insert(pos,l)
                            else:
                                linha.insert(pos+1,l) 
                                linhaant.insert(pos+1,l)                                
                #commitant = commitatual
        elif projatual != projant:
            if getattr(row, col) == 1:# and commitatual == 10:
                #linha.append('-1 -2 ' + col)
                linha.append('-1 -2')
                #linhaant.append(linha)
                coluna.append(linha)
                linha=[]
                linhaant=[]
                #linha.append(col)
                linha.append(df2.columns.get_loc(col)*1000)
                #linhaant.append(col)
                linhaant.append(df2.columns.get_loc(col)*1000)
                #contproj = contproj + 1
                #print('projs diferentes:','atual:', projatual,'anterior:', projant)
                projant = projatual
                commitant = commitatual
            elif getattr(row, col) == 0 and (commitatual != commitant):
                if len(linha) != 0:
                    linha.append('-1 -2')
                    #linhaant.append(col)
                    coluna.append(linha)
                    linha=[]
                    linhaant=[]
                    #print('entrou proj e commits diferentes', 'atual:', projatual,commitatual,'anterior:', projant,commitant )
                projant = projatual
                commitant = commitatual
            #novo   
            elif getattr(row, col) == 0 and (commitatual == commitant):
                if len(linha) != 0:
                    #linha.append('-1 -2')
                    #linhaant.append(col)
                    #coluna.append(linha)
                    #linha=[]
                    linhaant=[]
                    #print('entrou', 'atual:', projatual,commitatual,'anterior:', projant,commitant )
                projant = projatual
                commitant = commitatual

            contproj = contproj + 1
        #projant=projatual
        #commitant = 0
    projant = projatual 
    #print ('atual:', projatual,'anterior:', projant)
    #coluna.append(linha)
    #matriz.append(coluna)
    #linha=[]
    if row.Index == len(df2) - 1: # acrescentar em todos os algoritmos
        #print(row.Index, len(df2)-1)
        linha.append('-1 -2')
        coluna.append(linha)
        contproj = contproj + 1
#matriz.append(coluna)
print(len(linha))
#print(len(linhaant),linhaant)
#print(len(linha))
print(contproj)
print(coluna)

Entrou1: -1 -1 -1 3 [2000] [2]
Entrou1: -1 -1 -1 4 [2000] [2, 3000]
Entrou2: 1 -1 -1 3 [2, 3000, 4000] [2]
Entrou2: 2 -1 -1 4 [2, 3000, 4000] [2, 3]
Entrou1: -1 -1 -1 5 [2, 3000, 4000] [2, 3, 4]
Entrou2: -1 1 -1 3 [2, 3, 4, 5000] [2]
Entrou2: 1 -1 -1 4 [200, 4000] [3000]
Entrou2: -1 1 -1 4 [3000, 4] [2000, 300]
Entrou1: -1 -1 -1 3 ['-1'] [2000]
Entrou1: -1 -1 -1 5 [2000, 3000] [4000]
Entrou1: -1 -1 0 4 [400, 5] [3000]
15
3
[[2000, '-1', 2, 3000, 4000, '-1', 2, 3, 4, 5000, '-1', 2, 3, 400, 500, '-1 -2'], [2000, '-1', 200, 4000, '-1', 3000, 4, '-1', 2000, 300, 4, '-1 -2'], [2000, 3000, '-1', 200, 300, 4000, 5000, '-1', 400, 5, '-1', 3000, 4000, 500, '-1 -2']]

[[6000, 8000, 32000, 36000, '-1', 6, 8, 32, 36, 49000, '-1', 6, 8, 32, 36, 49, 50000, '-1', 6, 8, 32, 36, 4900, 5000, '-1', 6, 8, 32, 36, 49000, '-1', 6, 8, 32, 36, 4900, '-1', 6, 8, 32, 36, 50000, '-1', 6, 8, 32, 36, 49000, 5000, '-1', 6, 8, 32, 36, 4900, '-1', 6, 8, 32, 36, '-1 -2'], [12000, 24000, 27000, 34000, 36000, 38000, 41000, 43000, '-1', 12, 24, 27, 34, 36, 38, 41, 43, '-1', 12, 24, 27, 34, 36, 38, 41, 43, '-1', 12, 24, 27, 34, 36, 38, 41, 43, '-1', 12, 24, 27, 34, 36, 38, 41, 43, '-1', 12, 24, 27, 34, 36, 38, 41, 43, '-1', 12, 24, 27, 34, 36, 38, 41, 43, '-1', 12, 24, 27, 34, 36, 38, 41, 43, '-1', 12, 24, 27, 34, 36, 38, 41, 43, '-1', 12, 24, 27, 34, 36, 38, 41, 43, '-1 -2'], [6000, 8000, 9000, 14000, 18000, 24000, 26000, 27000, 28000, 31000, 32000, 33000, 36000, 37000, 41000, 43000, 47000, 48000, '-1', 6, 8, 9, 14, 18, 24, 26, 27, 28, 31, 32, 33, 36, 37, 41, 43, 47, 48, '-1', 6, 8, 9, 14, 18, 24, 26, 27, 28, 31, 32, 33, 36, 37, 41, 43, 47, 48, '-1', 6, 8, 9, 14, 18, 24, 26, 27, 28, 31, 32, 33, 36, 37, 41, 43, 47, 48, '-1', 6, 8, 9, 14, 18, 24, 26, 27, 28, 31, 32, 33, 36, 37, 41, 43, 47, 48, 52000, '-1', 6, 8, 9, 14, 18, 24, 26, 27, 28, 31, 32, 33, 36, 37, 41, 43, 47, 48, 52, '-1', 6, 8, 9, 14, 18, 24, 26, 27, 28, 31, 32, 33, 36, 37, 41, 43, 47, 48, 52, '-1', 6, 8, 9, 14, 18, 24, 26, 27, 28, 31, 32, 33, 36, 37, 41, 43, 47, 48, 5200, '-1', 6, 8, 9, 14, 18, 24, 26, 27, 28, 31, 32, 33, 36, 37, 41, 43, 47, 48, '-1', 6, 8, 9, 14, 18, 24, 26, 27, 28, 31, 32, 33, 36, 37, 41, 43, 47, 48, '-1 -2'], [14000, 24000, 27000, 28000, 33000, 34000, 36000, 37000, 47000, 48000, 53000, '-1', 14, 24, 27, 28, 33, 34, 36, 37, 47, 48, 53, '-1', 14, 24, 27, 28, 33, 34, 36, 37, 47, 48, 5300, '-1', 14, 24, 27, 28, 33, 34, 36, 37, 47, 48, 53000, '-1', 14, 24, 27, 28, 33, 34, 36, 37, 47, 48, 5300, '-1', 14, 24, 27, 28, 33, 34, 36, 37, 47, 48, 53000, '-1', 14, 24, 27, 28, 33, 34, 36, 37, 47, 48, 53, '-1', 14, 24, 27, 28, 33, 34, 36, 37, 47, 48, 5300, '-1', 14, 24, 27, 28, 33, 34, 36, 37, 47, 48, '-1', 14, 24, 27, 28, 33, 34, 36, 37, 47, 48, '-1 -2'], [32000, '-1', 32, '-1', 32, '-1', 32, '-1', 32, '-1', 32, '-1', 32, '-1', 32, '-1', 32, '-1', 32, '-1 -2'], [12000, 34000, 48000, '-1', 12, 34, 48, '-1', 12, 34, 48, '-1', 12, 34, 48, '-1', 12, 34, 48, '-1', 12, 34, 48, '-1', 12, 34, 48, '-1', 12, 34, 48, '-1', 12, 34, 48, '-1', 12, 34, 48, '-1 -2'], [6000, 8000, 9000, 28000, 32000, 36000, 41000, 47000, 48000, '-1', 6, 8, 9, 28, 32, 36, 41, 47, 48, '-1', 6, 8, 9, 28, 32, 36, 41, 47, 48, '-1', 6, 8, 9, 28, 32, 36, 41, 47, 48, '-1', 6, 8, 9, 28, 32, 36, 41, 47, 48, '-1', 6, 8, 9, 28, 32, 36, 41, 47, 48, '-1', 6, 8, 9, 28, 32, 36, 41, 47, 48, '-1', 6, 8, 9, 28, 32, 36, 41, 47, 48, '-1', 6, 8, 9, 28, 32, 36, 41, 47, 48, '-1', 6, 8, 9, 28, 32, 36, 41, 47, 48, '-1 -2'], [10000, '-1', 10, '-1', 10, '-1', 10, '-1', 10, '-1', 10, '-1', 10, '-1', 10, '-1', 10, '-1', 10, '-1 -2'], [9000, 18000, 36000, 43000, '-1', 24000, 27000, 3600, 900, 1800, 41000, 4300, '-1', 18000, 2400, 27, 32000, 36000, 41, 43000, '-1', 9000, 18, 24000, 27, 32, 36, 41, 4300, '-1', 9, 18, 24, 27, 32, 36, 41, 48000, '-1', 9, 18, 24, 27, 32, 36, 41, 48, '-1', 6000, 9, 18, 24, 26000, 27, 32, 33000, 36000, 37000, 41000, 48000, '-1', 6, 9, 18, 24, 26, 27, 32, 33, 36, 37, 41, 48, '-1', 6, 9, 18, 24, 26, 27, 28000, 32, 33, 36, 37, 41, 48000, '-1', 5000, 6, 9, 18, 24, 26, 27, 28, 32, 33, 36, 37, 41, 43000, 47000, 48000, '-1 -2'], [32000, '-1', 32, '-1', 32, '-1', 32, '-1', 32, '-1', 32, '-1', 32, '-1', 32, '-1', 32, '-1', 32, '-1 -2'], [10000, 36000, '-1', 10, 36, '-1', 10, 36, '-1', 10, 36, '-1', 10, 36, '-1', 10, 36, '-1', 10, 36, '-1', 10, 36, '-1', 10, 36, '-1', 10, 36, '-1 -2']]

[[6000, 8000, 32000, 36000, '-1', 6, 8, 32, 36, 49000, '-1', 6, 8, 32, 36, 49, 50000, '-1', 6, 8, 32, 36, 4900, 5000, '-1', 6, 8, 32, 36, 49000, '-1', 6, 8, 32, 36, 4900, '-1', 6, 8, 32, 36, 50000, '-1', 6, 8, 32, 36, 49000, 5000, '-1', 6, 8, 32, 36, 4900, '-1', 6, 8, 32, 36, '-1 -2'], [12000, 24000, 27000, 34000, 36000, 38000, 41000, 43000, '-1', 12, 24, 27, 34, 36, 38, 41, 43, '-1', 12, 24, 27, 34, 36, 38, 41, 43, '-1', 12, 24, 27, 34, 36, 38, 41, 43, '-1', 12, 24, 27, 34, 36, 38, 41, 43, '-1', 12, 24, 27, 34, 36, 38, 41, 43, '-1', 12, 24, 27, 34, 36, 38, 41, 43, '-1', 12, 24, 27, 34, 36, 38, 41, 43, '-1', 12, 24, 27, 34, 36, 38, 41, 43, '-1', 12, 24, 27, 34, 36, 38, 41, 43, '-1 -2'], [6000, 8000, 9000, 14000, 18000, 24000, 26000, 27000, 28000, 31000, 32000, 33000, 36000, 37000, 41000, 43000, 47000, 48000, '-1', 6, 8, 9, 14, 18, 24, 26, 27, 28, 31, 32, 33, 36, 37, 41, 43, 47, 48, '-1', 6, 8, 9, 14, 18, 24, 26, 27, 28, 31, 32, 33, 36, 37, 41, 43, 47, 48, '-1', 6, 8, 9, 14, 18, 24, 26, 27, 28, 31, 32, 33, 36, 37, 41, 43, 47, 48, '-1', 6, 8, 9, 14, 18, 24, 26, 27, 28, 31, 32, 33, 36, 37, 41, 43, 47, 48, 52000, '-1', 6, 8, 9, 14, 18, 24, 26, 27, 28, 31, 32, 33, 36, 37, 41, 43, 47, 48, 52, '-1', 6, 8, 9, 14, 18, 24, 26, 27, 28, 31, 32, 33, 36, 37, 41, 43, 47, 48, 52, '-1', 6, 8, 9, 14, 18, 24, 26, 27, 28, 31, 32, 33, 36, 37, 41, 43, 47, 48, 5200, '-1', 6, 8, 9, 14, 18, 24, 26, 27, 28, 31, 32, 33, 36, 37, 41, 43, 47, 48, '-1', 6, 8, 9, 14, 18, 24, 26, 27, 28, 31, 32, 33, 36, 37, 41, 43, 47, 48, '-1 -2'], [14000, 24000, 27000, 28000, 33000, 34000, 36000, 37000, 47000, 48000, 53000, '-1', 14, 24, 27, 28, 33, 34, 36, 37, 47, 48, 53, '-1', 14, 24, 27, 28, 33, 34, 36, 37, 47, 48, 5300, '-1', 14, 24, 27, 28, 33, 34, 36, 37, 47, 48, 53000, '-1', 14, 24, 27, 28, 33, 34, 36, 37, 47, 48, 5300, '-1', 14, 24, 27, 28, 33, 34, 36, 37, 47, 48, 53000, '-1', 14, 24, 27, 28, 33, 34, 36, 37, 47, 48, 53, '-1', 14, 24, 27, 28, 33, 34, 36, 37, 47, 48, 5300, '-1', 14, 24, 27, 28, 33, 34, 36, 37, 47, 48, '-1', 14, 24, 27, 28, 33, 34, 36, 37, 47, 48, '-1 -2'], [32000, '-1', 32, '-1', 32, '-1', 32, '-1', 32, '-1', 32, '-1', 32, '-1', 32, '-1', 32, '-1', 32, '-1 -2'], [12000, 34000, 48000, '-1', 12, 34, 48, '-1', 12, 34, 48, '-1', 12, 34, 48, '-1', 12, 34, 48, '-1', 12, 34, 48, '-1', 12, 34, 48, '-1', 12, 34, 48, '-1', 12, 34, 48, '-1', 12, 34, 48, '-1 -2'], [6000, 8000, 9000, 28000, 32000, 36000, 41000, 47000, 48000, '-1', 6, 8, 9, 28, 32, 36, 41, 47, 48, '-1', 6, 8, 9, 28, 32, 36, 41, 47, 48, '-1', 6, 8, 9, 28, 32, 36, 41, 47, 48, '-1', 6, 8, 9, 28, 32, 36, 41, 47, 48, '-1', 6, 8, 9, 28, 32, 36, 41, 47, 48, '-1', 6, 8, 9, 28, 32, 36, 41, 47, 48, '-1', 6, 8, 9, 28, 32, 36, 41, 47, 48, '-1', 6, 8, 9, 28, 32, 36, 41, 47, 48, '-1', 6, 8, 9, 28, 32, 36, 41, 47, 48, '-1 -2'], [10000, '-1', 10, '-1', 10, '-1', 10, '-1', 10, '-1', 10, '-1', 10, '-1', 10, '-1', 10, '-1', 10, '-1 -2'], [9000, 18000, 36000, 43000, '-1', 24000, 27000, 3600, 900, 1800, 41000, 4300, '-1', 18000, 2400, 27, 32000, 36000, 41, 43000, '-1', 9000, 18, 24000, 27, 32, 36, 41, 4300, '-1', 9, 18, 24, 27, 32, 36, 41, 48000, '-1', 9, 18, 24, 27, 32, 36, 41, 48, '-1', 6000, 9, 18, 24, 26000, 27, 32, 33000, 36000, 37000, 41000, 48000, '-1', 6, 9, 18, 24, 26, 27, 32, 33, 36, 37, 41, 48, '-1', 6, 9, 18, 24, 26, 27, 28000, 32, 33, 36, 37, 41, 48000, '-1', 5000, 6, 9, 18, 24, 26, 27, 28, 32, 33, 36, 37, 41, 43000, 47000, 48000, '-1 -2'], [32000, '-1', 32, '-1', 32, '-1', 32, '-1', 32, '-1', 32, '-1', 32, '-1', 32, '-1', 32, '-1', 32, '-1 -2'], [10000, 36000, '-1', 10, 36, '-1', 10, 36, '-1', 10, 36, '-1', 10, 36, '-1', 10, 36, '-1', 10, 36, '-1', 10, 36, '-1', 10, 36, '-1', 10, 36, '-1 -2']]

30
12
[[6000, 8000, 32000, 36000, '-1', 6, 8, 32, 36, 49000, '-1', 6, 8, 32, 36, 49, 50000, '-1', 6, 8, 32, 36, 4900, 5000, '-1', 6, 8, 32, 36, 49000, '-1', 6, 8, 32, 36, 4900, '-1', 6, 8, 32, 36, 50000, '-1', 6, 8, 32, 36, 49000, 5000, '-1', 6, 8, 32, 36, 4900, '-1', 6, 8, 32, 36, '-1 -2'], [12000, 24000, 27000, 34000, 36000, 38000, 41000, 43000, '-1', 12, 24, 27, 34, 36, 38, 41, 43, '-1', 12, 24, 27, 34, 36, 38, 41, 43, '-1', 12, 24, 27, 34, 36, 38, 41, 43, '-1', 12, 24, 27, 34, 36, 38, 41, 43, '-1', 12, 24, 27, 34, 36, 38, 41, 43, '-1', 12, 24, 27, 34, 36, 38, 41, 43, '-1', 12, 24, 27, 34, 36, 38, 41, 43, '-1', 12, 24, 27, 34, 36, 38, 41, 43, '-1', 12, 24, 27, 34, 36, 38, 41, 43, '-1 -2'], [6000, 8000, 9000, 14000, 18000, 24000, 26000, 27000, 28000, 31000, 32000, 33000, 36000, 37000, 41000, 43000, 47000, 48000, '-1', 6, 8, 9, 14, 18, 24, 26, 27, 28, 31, 32, 33, 36, 37, 41, 43, 47, 48, '-1', 6, 8, 9, 14, 18, 24, 26, 27, 28, 31, 32, 33, 36, 37, 41, 43, 47, 48, '-1', 6, 8, 9, 14, 18, 24, 26, 27, 28, 31, 32, 33, 36, 37, 41, 43, 47, 48, '-1', 6, 8, 9, 14, 18, 24, 26, 27, 28, 31, 32, 33, 36, 37, 41, 43, 47, 48, 52000, '-1', 6, 8, 9, 14, 18, 24, 26, 27, 28, 31, 32, 33, 36, 37, 41, 43, 47, 48, 52, '-1', 6, 8, 9, 14, 18, 24, 26, 27, 28, 31, 32, 33, 36, 37, 41, 43, 47, 48, 52, '-1', 6, 8, 9, 14, 18, 24, 26, 27, 28, 31, 32, 33, 36, 37, 41, 43, 47, 48, 5200, '-1', 6, 8, 9, 14, 18, 24, 26, 27, 28, 31, 32, 33, 36, 37, 41, 43, 47, 48, '-1', 6, 8, 9, 14, 18, 24, 26, 27, 28, 31, 32, 33, 36, 37, 41, 43, 47, 48, '-1 -2'], [14000, 24000, 27000, 28000, 33000, 34000, 36000, 37000, 47000, 48000, 53000, '-1', 14, 24, 27, 28, 33, 34, 36, 37, 47, 48, 53, '-1', 14, 24, 27, 28, 33, 34, 36, 37, 47, 48, 5300, '-1', 14, 24, 27, 28, 33, 34, 36, 37, 47, 48, 53000, '-1', 14, 24, 27, 28, 33, 34, 36, 37, 47, 48, 5300, '-1', 14, 24, 27, 28, 33, 34, 36, 37, 47, 48, 53000, '-1', 14, 24, 27, 28, 33, 34, 36, 37, 47, 48, 53000, '-1', 14, 24, 27, 28, 33, 34, 36, 37, 47, 48, 5300, '-1', 14, 24, 27, 28, 33, 34, 36, 37, 47, 48, '-1', 14, 24, 27, 28, 33, 34, 36, 37, 47, 48, '-1 -2'], [32000, '-1', 32, '-1', 32, '-1', 32, '-1', 32, '-1', 32, '-1', 32, '-1', 32, '-1', 32, '-1', 32, '-1 -2'], [12000, 34000, 48000, '-1', 12, 34, 48, '-1', 12, 34, 48, '-1', 12, 34, 48, '-1', 12, 34, 48, '-1', 12, 34, 48, '-1', 12, 34, 48, '-1', 12, 34, 48, '-1', 12, 34, 48, '-1', 12, 34, 48, '-1 -2'], [6000, 8000, 9000, 28000, 32000, 36000, 41000, 47000, 48000, '-1', 6, 8, 9, 28, 32, 36, 41, 47, 48, '-1', 6, 8, 9, 28, 32, 36, 41, 47, 48, '-1', 6, 8, 9, 28, 32, 36, 41, 47, 48, '-1', 6, 8, 9, 28, 32, 36, 41, 47, 48, '-1', 6, 8, 9, 28, 32, 36, 41, 47, 48, '-1', 6, 8, 9, 28, 32, 36, 41, 47, 48, '-1', 6, 8, 9, 28, 32, 36, 41, 47, 48, '-1', 6, 8, 9, 28, 32, 36, 41, 47, 48, '-1', 6, 8, 9, 28, 32, 36, 41, 47, 48, '-1 -2'], [10000, '-1', 10, '-1', 10, '-1', 10, '-1', 10, '-1', 10, '-1', 10, '-1', 10, '-1', 10, '-1', 10, '-1 -2'], [9000, 18000, 36000, 43000, '-1', 24000, 27000, 3600, 900, 1800, 41000, 4300, '-1', 18000, 2400, 27, 32000, 36000, 41, 43000, '-1', 9000, 18000, 24000, 27, 32, 36000, 41, 4300, '-1', 9000, 18000, 24000, 27, 32, 36000, 41, 48000, '-1', 9000, 18000, 24000, 27, 32, 36000, 41, 48, '-1', 6000, 9000, 18000, 24000, 26000, 27, 32, 33000, 36000, 37000, 41, 48, '-1', 6, 9000, 18000, 24000, 26, 27, 32, 33, 36000, 37, 41, 48, '-1', 6, 9000, 18000, 24000, 26, 27, 28000, 32, 33, 36000, 37, 41, 48, '-1', 5000, 6, 9000, 18000, 24000, 26, 27, 28, 32, 33, 36000, 37, 41, 43000, 47000, 48, '-1 -2'], [32000, '-1', 32, '-1', 32, '-1', 32, '-1', 32, '-1', 32, '-1', 32, '-1', 32, '-1', 32, '-1', 32, '-1 -2'], [10000, 36000, '-1', 10, 36, '-1', 10, 36, '-1', 10, 36, '-1', 10, 36, '-1', 10, 36, '-1', 10, 36, '-1', 10, 36, '-1', 10, 36, '-1', 10, 36, '-1 -2']]

Ultimo algoritmo com o teste do sample e que precisa de ajustes

In [20]:
coluna=[]

proj = 0
projant = 'xxxx'
commitant = 0
linha=[]
linhaant = []
contproj = 0
noBD = -2
noBDant = -2
for row in df2.itertuples():
    #print(row.Index) 
    #print((col)
    commitant = 0
    for col in df2.columns:
        if col == "PROJECTS":
            #proj = proj + 1
            #linha.append(getattr(row, col))
            #print(getattr(row, col))
            projatual = getattr(row, col)
            #print('atual novo:', projatual, 'anterior:', projant)
            
        elif col == "COMMITS":
            commitatual = getattr(row, col)
            #commitant = commitatual
            #linha.append(getattr(row, col))
            #print('Commit:',getattr(row, col))
        elif projatual == projant or row.Index == 0:# projant == 'xxxx':
            if (commitatual == commitant) :
                if (getattr(row, col) == 1):
                    inBD = verify_BD(df2.columns.get_loc(col)*1000,linha)
                    outBD= verify_BD(df2.columns.get_loc(col)*100,linha)
                    #try:
                            #inBD = linha.index(df2.columns.get_loc(col)*1000)
                            
                            #BD = linha.index(df2.columns.get_loc(col))
                    #except:
                            #inBD = -1
                            #BD = -1
                    #print('Entrou if 1 commits iguais',linha, inBD, df2.columns.get_loc(col)*1000)
                    if inBD < 0 or (inBD >= 0 and outBD >= 0): #and BD < 0:
                            #print('Entrou2:',linha, inBD, df2.columns.get_loc(col)*1000)
                            linha.append(df2.columns.get_loc(col)*1000)
                            linhaant.append(df2.columns.get_loc(col)*1000)#inclui agora
                            #print('Entrou2:',linha, inBD, BD, df2.columns.get_loc(col))
                    else:# or BD >= 0): #or ((inBD >= 0 and BD >= 0)) : #and row.index == 0:
                            #linha.append('No'+col)
                            #linha.append(-df2.columns.get_loc(col))
                            #print('Entrou1:',linha, inBD, df2.columns.get_loc(col)*1000)
                            linha.append(df2.columns.get_loc(col))
                            linhaant.append(df2.columns.get_loc(col))      
                   

                    #print('projs iguais e commits iguais','atual:', projatual,'anterior:', projant, commitatual, commitant, row.Index)
                    #print(df2[x])
                    #print('Database:', col)
                    #linha.append(col)
                    #linha.append(df2.columns.get_loc(col))
                    #linhaant.append(col)
                    #linhaant.append(df2.columns.get_loc(col))
                    #print('entrou commits')
                    commitant = commitatual
                elif getattr(row, col) == 0:
                    #Se for a primeira coluna e a linhaant tinha BD
                    if len(linha) == 0 and len(linhaant) != 0:
                        #print("Se primeira coluna",len(linha),len(linhaant))
                        inBD = verify_BD(df2.columns.get_loc(col)*1000, linha)
                        BD = verify_BD(df2.columns.get_loc(col), linha)
                        outBD =  verify_BD(df2.columns.get_loc(col)*100, linha)
                        #print("Entrou bd1",linha, df2.columns.get_loc(col),noBD)
                        #try:
                            #noBD = linhaant.index(col)
                            #noBD = linhaant.index(df2.columns.get_loc(col))
                        #except:
                            #   noBD = -1
                        #if outBD >= 0: #and row.index == 0:
                        if BD >= 0 or (inBD >= 0 and outBD < 0):
                            linha.append(df2.columns.get_loc(col)*100)
                            linhaant.append(df2.columns.get_loc(col)*100)#inclui agora
                            #falta apend na linha anterior
                        #print('primeira coluna',noBD, linha, col)
                        #print('entrou 1',noBD, noBDin, df2.columns.get_loc(col)*1000, linha,)
                        commitant = commitatual
                    elif len(linha) != 0 and len(linhaant) != 0:
                        inBD = verify_BD(df2.columns.get_loc(col)*1000, linha)
                        BD = verify_BD(df2.columns.get_loc(col), linha)
                        outBD =  verify_BD(df2.columns.get_loc(col)*100, linha)
                        #print("Entrou bd1",linha, df2.columns.get_loc(col),noBD)
                        #try:
                            #noBD = linhaant.index(col)
                            #noBD = linhaant.index(df2.columns.get_loc(col))
                        #except:
                            #   noBD = -1
                        #if outBD >= 0: #and row.index == 0:
                        if BD >= 0 or (inBD >= 0 and outBD < 0):
                            linha.append(df2.columns.get_loc(col)*100)
                            linhaant.append(df2.columns.get_loc(col)*100)#inclui agora
                        #Comentado daqui em diante
                        #outBD =  verify_BD(df2.columns.get_loc(col), linha)
                        #print("Entrou bd1",linha, df2.columns.get_loc(col),noBD)
                        #if outBD < 0:
                            #Verficando se na linha tinha o BD*1000
                         #   outBD =  verify_BD(int(df2.columns.get_loc(col)*1000), linha)
                            #print("Entrou bd2",df2.columns.get_loc(col),noBD,linha)
                        #print('TambÃ©m entra aqui',noBD, df2.columns.get_loc(col), linha)
                        #if outBD >= 0:# or noBDm >=0:# and noBDin >=0: #and row.index == 0:
                         #   linha.append(df2.columns.get_loc(col)*100)
                          #  linhaant.append(df2.columns.get_loc(col)*100)#inclui agora
                            #print('entrou 2',noBD, noBDin, df2.columns.get_loc(col)*1000, linha)
                        commitant = commitatual   
            elif (commitatual != commitant):
                if getattr(row, col) == 1:
                    #print('projs iguais ecommits diferentes','atual:', projatual,'anterior:', projant, commitatual, commitant, row.Index )
                    if row.Index == 0 or len(linha) == 0:
                        inBD = verify_BD(df2.columns.get_loc(col)*1000,linha)
                        outBD= verify_BD(df2.columns.get_loc(col)*100,linha)
                        #try:
                         #   inBD =  linha.index(df2.columns.get_loc(col)*1000)
                            #BD = linha.index(df2.columns.get_loc(col))
                       # except:
                                #BD = -1
                        #        inBD = -1
                        #print('Entrou if 1 commit diferentes', inBD, df2.columns.get_loc(col), linha)
                        if inBD < 0 or outBD >=0:
                            linha.append(df2.columns.get_loc(col)*1000)
                            linhaant.append(df2.columns.get_loc(col)*1000)#inclui agora
                        else: 
                            linha.append(df2.columns.get_loc(col))
                            linhaant.append(df2.columns.get_loc(col))
                       
                    else:
                        linha.append('-1')
                        #linha.append(col)
                        #linha.append(df2.columns.get_loc(col))
                        linhaant.append('-1')
                        #linhaant.append(col)
                        #linhaant.append(df2.columns.get_loc(col))
                        inBD = verify_BD(df2.columns.get_loc(col)*1000,linha)
                        outBD= verify_BD(df2.columns.get_loc(col)*100,linha)
                        #try:
                         #   inBD =  linha.index(df2.columns.get_loc(col)*1000)
                            #BD = linha.index(df2.columns.get_loc(col))
                        #except:
                                #BD = -1
                                #inBD = -1
                        #print('Entrou if 2 commit diferentes',inBD,df2.columns.get_loc(col),linha)
                        if inBD < 0 or outBD >=0:
                            linha.append(df2.columns.get_loc(col)*1000)
                            linhaant.append(df2.columns.get_loc(col)*1000)#inclui agora
                            #print('entrou inbd 1 < 0',inBD,df2.columns.get_loc(col),linha)
                        else: 
                            linha.append(df2.columns.get_loc(col))
                            linhaant.append(df2.columns.get_loc(col))
                            #print('entrou inbd 2 < 0',inBD,df2.columns.get_loc(col),linha)
                        
                    commitant = commitatual
                elif getattr(row, col) == 0:
                    list1 = []
                    list2 = []
                    count = 0
                    start = 0
                    delimant= 0
                    listaant = []
                    newList = []             
                    #if linha == linhaant and linha != 0:
                    for i,l in enumerate (linha):
                        if l == '-1' and count == 0:
                            list1 = linha[:i]
                            list2 = linha[i+1:]
                            delimant = i
                            count = count+1
                            #print('entrou no 1',linha, list1, list2, i, count)
                        elif l == '-1' and count > 0 :
                            start = i - delimant
                            list1 = linha[start:i]                            
                            list2 = linha[i+1:]
                            count = count + 1
                            delimant = i
                            #print('entrou no 2',linha, list1, list2, i, count)
                        #print(newList,list1,list2)
                        if len(list1)!=0 and len(list2)!=0 and (i == len(linha)-1):
                            delim ='-1'
                            if delim not in list1 and delim not in list2:
                                newList = [int (l) for l in list1 if l not in list2 ]
                                #print(newList,list1,list2)
                                if newList != 0:
                                    #newList = [int (i) *100 if i %1000 != 0 else int(i/1000) for i in newList] #[int(i) * 100 for i in lista1]
                                    for i,n in enumerate (newList):
                                        if  n % 1000 == 0:
                                            #print('Entrou 1 antes',newList[i],newList)
                                            if (n not in list2) and (int(n/1000) not in list2):
                                                newList[i] = int (n/1000)
                                            #elif n/1000 not in list2:
                                                #newList[i] = int (n/1000)
                                                #print('Entrou 1',newList[i],n,newList,list2)
                                        elif n % 100 == 0:
                                            #print('Entrou 2 antes',newList[i],newList)
                                            newList[i] = int(n/100)
                                            #print('Entrou 2',newList[i],newList)

                                    newList = [int (i) *100 if i %1000 != 0 else i/1000 for i in newList ] #[int(i) * 100 for i in lista1]
                                    #newList = [int (i) for i in newList if i %1000 != 0] 
                                    #print(linha, list1 , list2, i,count, len(list1),len(list2),newList)
                                    ##[int(i) * 100 for i in lista1]
                                    #newList = [int (i) *100 if (i%1000 == 0) else int(i*10) for i in list1]
                                    #print(linha, list1 , list2, i,count, len(list1),len(list2),newList)
                                #listaant = newList
                    if len(newList) != 0: #and list1 not in newList:# #and newList != listaant:
                        newList2 = [int (l) for l in newList  if l not in linha ] #if l*10 not in linha] # or l*100
                        #print(linha, list1, list2, i,count, len(list1),len(list2), newList, newList2)
                        #if newList2 == newList:
                        #lista = ''
                        #lista = str(newList2)
                        #print(linha,  newList, len(newList),len(newList2), newList2) 
                        pos = len(linha)-len(newList2) 
                        #linha.insert(pos,newList2)
                        for i,l in enumerate (newList2):
                            if i == 0 and linha[pos] != '-1':           
                                linha.insert(pos,l)
                                linhaant.insert(pos,l)
                            else:
                                linha.insert(pos+1,l) 
                                linhaant.insert(pos+1,l)                                
                #commitant = commitatual
        elif projatual != projant:
            if getattr(row, col) == 1:# and commitatual == 10:
                #linha.append('-1 -2 ' + col)
                linha.append('-1 -2')
                #linhaant.append(linha)
                coluna.append(linha)
                linha=[]
                linhaant=[]
                #linha.append(col)
                linha.append(df2.columns.get_loc(col)*1000)
                #linhaant.append(col)
                linhaant.append(df2.columns.get_loc(col)*1000)
                #contproj = contproj + 1
                #print('projs diferentes:','atual:', projatual,'anterior:', projant)
                projant = projatual
                commitant = commitatual
            elif getattr(row, col) == 0 and (commitatual != commitant):
                if len(linha) != 0:
                    linha.append('-1 -2')
                    #linhaant.append(col)
                    coluna.append(linha)
                    linha=[]
                    linhaant=[]
                    #print('entrou proj e commits diferentes', 'atual:', projatual,commitatual,'anterior:', projant,commitant )
                projant = projatual
                commitant = commitatual
            #novo   
            elif getattr(row, col) == 0 and (commitatual == commitant):
                if len(linha) != 0:
                    #linha.append('-1 -2')
                    #linhaant.append(col)
                    #coluna.append(linha)
                    #linha=[]
                    linhaant=[]
                    #print('entrou', 'atual:', projatual,commitatual,'anterior:', projant,commitant )
                projant = projatual
                commitant = commitatual

            contproj = contproj + 1
        #projant=projatual
        #commitant = 0
    projant = projatual 
    #print ('atual:', projatual,'anterior:', projant)
    #coluna.append(linha)
    #matriz.append(coluna)
    #linha=[]
    if row.Index == len(df2) - 1: # acrescentar em todos os algoritmos
        #print(row.Index, len(df2)-1)
        linha.append('-1 -2')
        coluna.append(linha)
        contproj = contproj + 1
#matriz.append(coluna)
print(len(linha))
#print(len(linhaant),linhaant)
#print(len(linha))
print(contproj)
print(coluna)

30
12
[[6000, 8000, 32000, 36000, '-1', 6, 8, 32, 36, 49000, '-1', 6, 8, 32, 36, 49, 50000, '-1', 6, 8, 32, 36, 4900, 5000, '-1', 6, 8, 32, 36, 49000, '-1', 6, 8, 32, 36, 4900, '-1', 6, 8, 32, 36, 4900, 50000, '-1', 6, 8, 32, 36, 49000, '-1', 6, 8, 32, 36, 4900, '-1', 6, 8, 32, 36, 4900, '-1 -2'], [12000, 24000, 27000, 34000, 36000, 38000, 41000, 43000, '-1', 12, 24, 27, 34, 36, 38, 41, 43, '-1', 12, 24, 27, 34, 36, 38, 41, 43, '-1', 12, 24, 27, 34, 36, 38, 41, 43, '-1', 12, 24, 27, 34, 36, 38, 41, 43, '-1', 12, 24, 27, 34, 36, 38, 41, 43, '-1', 12, 24, 27, 34, 36, 38, 41, 43, '-1', 12, 24, 27, 34, 36, 38, 41, 43, '-1', 12, 24, 27, 34, 36, 38, 41, 43, '-1', 12, 24, 27, 34, 36, 38, 41, 43, '-1 -2'], [6000, 8000, 9000, 14000, 18000, 24000, 26000, 27000, 28000, 31000, 32000, 33000, 36000, 37000, 41000, 43000, 47000, 48000, '-1', 6, 8, 9, 14, 18, 24, 26, 27, 28, 31, 32, 33, 36, 37, 41, 43, 47, 48, '-1', 6, 8, 9, 14, 18, 24, 26, 27, 28, 31, 32, 33, 36, 37, 41, 43, 47, 48, '-1', 6, 8, 9, 14, 18, 24, 26, 27, 28, 31, 32, 33, 36, 37, 41, 43, 47, 48, '-1', 6, 8, 9, 14, 18, 24, 26, 27, 28, 31, 32, 33, 36, 37, 41, 43, 47, 48, 52000, '-1', 6, 8, 9, 14, 18, 24, 26, 27, 28, 31, 32, 33, 36, 37, 41, 43, 47, 48, 52, '-1', 6, 8, 9, 14, 18, 24, 26, 27, 28, 31, 32, 33, 36, 37, 41, 43, 47, 48, 52, '-1', 6, 8, 9, 14, 18, 24, 26, 27, 28, 31, 32, 33, 36, 37, 41, 43, 47, 48, 5200, '-1', 6, 8, 9, 14, 18, 24, 26, 27, 28, 31, 32, 33, 36, 37, 41, 43, 47, 48, 5200, '-1', 6, 8, 9, 14, 18, 24, 26, 27, 28, 31, 32, 33, 36, 37, 41, 43, 47, 48, 5200, '-1 -2'], [14000, 24000, 27000, 28000, 33000, 34000, 36000, 37000, 47000, 48000, 53000, '-1', 14, 24, 27, 28, 33, 34, 36, 37, 47, 48, 53, '-1', 14, 24, 27, 28, 33, 34, 36, 37, 47, 48, 5300, '-1', 14, 24, 27, 28, 33, 34, 36, 37, 47, 48, 53000, '-1', 14, 24, 27, 28, 33, 34, 36, 37, 47, 48, 5300, '-1', 14, 24, 27, 28, 33, 34, 36, 37, 47, 48, 53000, '-1', 14, 24, 27, 28, 33, 34, 36, 37, 47, 48, 53000, '-1', 14, 24, 27, 28, 33, 34, 36, 37, 47, 48, 5300, '-1', 14, 24, 27, 28, 33, 34, 36, 37, 47, 48, 5300, '-1', 14, 24, 27, 28, 33, 34, 36, 37, 47, 48, 5300, '-1 -2'], [32000, '-1', 32, '-1', 32, '-1', 32, '-1', 32, '-1', 32, '-1', 32, '-1', 32, '-1', 32, '-1', 32, '-1 -2'], [12000, 34000, 48000, '-1', 12, 34, 48, '-1', 12, 34, 48, '-1', 12, 34, 48, '-1', 12, 34, 48, '-1', 12, 34, 48, '-1', 12, 34, 48, '-1', 12, 34, 48, '-1', 12, 34, 48, '-1', 12, 34, 48, '-1 -2'], [6000, 8000, 9000, 28000, 32000, 36000, 41000, 47000, 48000, '-1', 6, 8, 9, 28, 32, 36, 41, 47, 48, '-1', 6, 8, 9, 28, 32, 36, 41, 47, 48, '-1', 6, 8, 9, 28, 32, 36, 41, 47, 48, '-1', 6, 8, 9, 28, 32, 36, 41, 47, 48, '-1', 6, 8, 9, 28, 32, 36, 41, 47, 48, '-1', 6, 8, 9, 28, 32, 36, 41, 47, 48, '-1', 6, 8, 9, 28, 32, 36, 41, 47, 48, '-1', 6, 8, 9, 28, 32, 36, 41, 47, 48, '-1', 6, 8, 9, 28, 32, 36, 41, 47, 48, '-1 -2'], [10000, '-1', 10, '-1', 10, '-1', 10, '-1', 10, '-1', 10, '-1', 10, '-1', 10, '-1', 10, '-1', 10, '-1 -2'], [9000, 18000, 36000, 43000, '-1', 24000, 27000, 3600, 900, 1800, 41000, 4300, '-1', 18000, 2400, 27, 32000, 36000, 41, 43000, '-1', 9000, 18000, 24000, 27, 32, 36000, 41, '-1', 9000, 18000, 24000, 27, 32, 36000, 41, 48000, '-1', 9000, 18000, 24000, 27, 32, 36000, 41, 48, '-1', 6000, 9000, 18000, 24000, 26000, 27, 32, 33000, 36000, 37000, 41, 48, '-1', 6, 9000, 18000, 24000, 26, 27, 32, 33, 36000, 37, 41, 48, '-1', 6, 9000, 18000, 24000, 26, 27, 28000, 32, 33, 36000, 37, 41, 48, '-1', 5000, 6, 9000, 18000, 24000, 26, 27, 28, 32, 33, 36000, 37, 41, 43000, 47000, 48, '-1 -2'], [32000, '-1', 32, '-1', 32, '-1', 32, '-1', 32, '-1', 32, '-1', 32, '-1', 32, '-1', 32, '-1', 32, '-1 -2'], [10000, 36000, '-1', 10, 36, '-1', 10, 36, '-1', 10, 36, '-1', 10, 36, '-1', 10, 36, '-1', 10, 36, '-1', 10, 36, '-1', 10, 36, '-1', 10, 36, '-1 -2']]

In [57]:
#file = open('input_sampletests_final.txt', "w")
file = open('input_spmf_final.txt', "w")
#dict_col
dict = []
#file = open("input_sequencial_nb_neg.txt", "w")
specialChars = "[',']" # Para retirar estes caracteres que sÃ£o incluÃ­dos pelo array
#for dict in dict_col: # Writes to file
 #   for specialChar in specialChars:
dict = str(dict_col).replace("[['",'')
dict = str(dict).replace("']]",'\n')
file.write(str(dict).replace("', '",'\n'))
#coluna.insert(0,str(dict_col))
for values in coluna: # Writes to file
    for specialChar in specialChars:
        values = str(values).replace(specialChar,'')
    file.write(str(values) + '\n')
file.close()