In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import os
from util import HISTORICAL_FILE_JOIN, RESOURCE_DIR, SEQ_PATTERNS_DIR

This script converts the historical_join dataset to the file format required by the SPMF library. At the end, it gives instructions for generating sequential patterns using the SPMF.jar file located in db-mining/resources/seq_patterns.

In [2]:
df = pd.read_excel(HISTORICAL_FILE_JOIN, keep_default_na=False)
#df = pd.read_excel( SEQ_PATTERNS_DIR + os.sep +'testes/teste_historical_init.xlsx', keep_default_na=False)# 24/09/2022

#df = pd.read_excel('hist_sample_teste6.xlsx', keep_default_na=False)
#df = pd.read_excel('hist_sample_teste5.xlsx', keep_default_na=False)
#df = pd.read_excel('hist_sample_teste4.xlsx', keep_default_na=False)
#df = pd.read_excel('hist_sample_teste3.xlsx', keep_default_na=False)
#df = pd.read_excel('hist_sample_teste2.xlsx', keep_default_na=False)
#df3 = pd.read_excel('historical_sample_join2.xlsx',keep_default_na=False)
#df4 = pd.read_excel('historical_tests_2proj.xlsx',keep_default_na=False)
#reads projects from Excel file

len(df)

3170

In [3]:
#df['PROJECTS'].unique()
selecao = df['PROJECTS'] == 'android'
dfteste = df[selecao]
dfteste

,PROJECTS,COMMITS,Microsoft Azure Table Storage,MySQL_Maria DB,HyperSQL,MarkLogic,MS SQL Server_Microsoft Azure SQL Database,FileMaker,Singlestore,Riak KV,...,ClickHouse,Vertica,Teradata,PostgreSQL_ CockroachDB,PostGIS,Etcd,Join_Ignite-Sql,Join_Ignite-NoSql,Join_Virtuoso-Sql,Join_Virtuoso-NoSql
800,android,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
801,android,2,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
802,android,3,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
803,android,4,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
804,android,5,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
805,android,6,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
806,android,7,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
807,android,8,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
808,android,9,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
809,android,10,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2110,android,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2111,android,2,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2112,android,3,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2113,android,4,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2114,android,5,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2115,android,6,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2116,android,7,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2117,android,8,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2118,android,9,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2119,android,10,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2290,android,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2291,android,2,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2292,android,3,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2293,android,4,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2294,android,5,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2295,android,6,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2296,android,7,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2297,android,8,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2298,android,9,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2299,android,10,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
df.columns

Index(['PROJECTS', 'COMMITS', 'Microsoft Azure Table Storage',
       'MySQL_Maria DB', 'HyperSQL', 'MarkLogic',
       'MS SQL Server_Microsoft Azure SQL Database', 'FileMaker',
       'Singlestore', 'Riak KV', 'Redis', 'Aerospike',
       'Google Cloud Datastore', 'Neo4j', 'H2', 'HBase', 'ArangoDB', 'SapHana',
       'Oracle', 'DynamoDB', 'Firebird', 'Informix', 'Ingres', 'IBM DB2',
       'Couchbase', 'GoogleCloudFilestore', 'Kdb+', 'Interbase',
       'Firebase Realtime', 'MongoDB', 'Hazelcast', 'Impala', 'Influx DB',
       'SQLite', 'Snowflake', 'Realm', 'Cassandra', 'SAP SQL Anywhere',
       'Microsoft Azure CosmosDB', 'MS Access', 'SAP Adaptive Server',
       'CouchDB', 'ClickHouse', 'Vertica', 'Teradata',
       'PostgreSQL_ CockroachDB', 'PostGIS', 'Etcd', 'Join_Ignite-Sql',
       'Join_Ignite-NoSql', 'Join_Virtuoso-Sql', 'Join_Virtuoso-NoSql'],
      dtype='object')

In [5]:
#df2.rename(columns={'MS Access': 'MS_Access', 'IBM DB2': 'IBM_DB2','Cosmos BD':'Cosmos_BD','MS SQL Server':'MS_SQL_Server'}, inplace=True)
df.rename(columns={'Join_Ignite-Sql':'Join_Ignite_Sql','Join_Ignite-NoSql':'Join_Ignite_NoSql','Join_MarkLogic-Sql':'Join_MarkLogic_Sql',
                    'Join_MarkLogic-NoSql':'Join_MarkLogic_NoSql','Join_Virtuoso-Sql':'Join_Virtuoso_Sql','Join_Virtuoso-NoSql':'Join_Virtuoso_NoSql'}, inplace=True)
df.rename(columns={'Microsoft Azure Table Storage': 'MicrosoftAzureTableStorage'}, inplace=True)
df.rename(columns={'IBM DB2':'IBM_DB2','Firebase Realtime':'FirebaseRealtime'}, inplace=True)
df.rename(columns={'Influx DB':'Influx_DB', 'Amazon Redshift':'AmazonRedshift','MS SQL Server': 'MS_SQL_Server'}, inplace=True)
df.rename(columns={'Microsoft Azure CosmosDB':'MicrosoftAzureCosmosDB', 'MS Access':'MS_Access','SAP Adaptive Server':'SAPAdaptiveServer'}, inplace=True)
df.rename(columns={'Google Cloud Datastore': 'GoogleCloudDatastore','Riak KV':'Riak_KV', 'Google BigQuery':'GoogleBigQuery'}, inplace=True)
df.rename(columns={'MySQL_Maria DB': 'MySQL_MariaDB', 'MS SQL Server_Microsoft Azure SQL Database': 'MSSQLServer_MicrosoftAzureSQLDatabase', 'Kdb+': 'Kdb'}, inplace=True)
df.rename(columns={'SAP SQL Anywhere': 'SAPSQLAnywhere', 'PostgreSQL_ CockroachDB': 'PostgreSQL_CockroachDB'}, inplace=True)

print(df.columns)

Index(['PROJECTS', 'COMMITS', 'MicrosoftAzureTableStorage', 'MySQL_MariaDB',
       'HyperSQL', 'MarkLogic', 'MSSQLServer_MicrosoftAzureSQLDatabase',
       'FileMaker', 'Singlestore', 'Riak_KV', 'Redis', 'Aerospike',
       'GoogleCloudDatastore', 'Neo4j', 'H2', 'HBase', 'ArangoDB', 'SapHana',
       'Oracle', 'DynamoDB', 'Firebird', 'Informix', 'Ingres', 'IBM_DB2',
       'Couchbase', 'GoogleCloudFilestore', 'Kdb', 'Interbase',
       'FirebaseRealtime', 'MongoDB', 'Hazelcast', 'Impala', 'Influx_DB',
       'SQLite', 'Snowflake', 'Realm', 'Cassandra', 'SAPSQLAnywhere',
       'MicrosoftAzureCosmosDB', 'MS_Access', 'SAPAdaptiveServer', 'CouchDB',
       'ClickHouse', 'Vertica', 'Teradata', 'PostgreSQL_CockroachDB',
       'PostGIS', 'Etcd', 'Join_Ignite_Sql', 'Join_Ignite_NoSql',
       'Join_Virtuoso_Sql', 'Join_Virtuoso_NoSql'],
      dtype='object')

In [6]:
df2 = df.copy()
print(df2.columns)

Index(['PROJECTS', 'COMMITS', 'MicrosoftAzureTableStorage', 'MySQL_MariaDB',
       'HyperSQL', 'MarkLogic', 'MSSQLServer_MicrosoftAzureSQLDatabase',
       'FileMaker', 'Singlestore', 'Riak_KV', 'Redis', 'Aerospike',
       'GoogleCloudDatastore', 'Neo4j', 'H2', 'HBase', 'ArangoDB', 'SapHana',
       'Oracle', 'DynamoDB', 'Firebird', 'Informix', 'Ingres', 'IBM_DB2',
       'Couchbase', 'GoogleCloudFilestore', 'Kdb', 'Interbase',
       'FirebaseRealtime', 'MongoDB', 'Hazelcast', 'Impala', 'Influx_DB',
       'SQLite', 'Snowflake', 'Realm', 'Cassandra', 'SAPSQLAnywhere',
       'MicrosoftAzureCosmosDB', 'MS_Access', 'SAPAdaptiveServer', 'CouchDB',
       'ClickHouse', 'Vertica', 'Teradata', 'PostgreSQL_CockroachDB',
       'PostGIS', 'Etcd', 'Join_Ignite_Sql', 'Join_Ignite_NoSql',
       'Join_Virtuoso_Sql', 'Join_Virtuoso_NoSql'],
      dtype='object')

Generating the dictionary with the names of the databases

In [7]:
dict_col=[]
#for row in df2.itertuples():
    #print(row.index()) 
    #print((col)
linha=[]
for col in df2.columns:
    #linha=[]
    if df2.columns.get_loc(col) == 0:
        #linha.append(df2.PROJECTS)
        linha.append('@CONVERTED_FROM_TEXT')
    elif df2.columns.get_loc(col) > 1: #@ITEM=1=apple
        #linha=[]
        linha.append('@ITEM='+ str(df2.columns.get_loc(col)*10000)+ '=INIT' + col)
        linha.append('@ITEM='+ str(df2.columns.get_loc(col)*1000)+ '=IN' + col)
        linha.append('@ITEM='+ str(df2.columns.get_loc(col))+ '=' + col)
        #linha.append('@ITEM='+ str(df2.columns.get_loc(col)*10000)+ '=INIT' + col + df2.PROJECTS)
        #linha.append('@ITEM='+ str(df2.columns.get_loc(col)*1000)+ '=IN' + col + df2.PROJECTS)
        #linha.append('@ITEM='+ str(df2.columns.get_loc(col))+ '=' + col + df2.PROJECTS)
        #dict_col.append(linha)
        #linha=[]
        #Da forma como mudei aqui, os projetos ainda irão se perder, talvez eu tenha que add o id dos projetos ao final da concatenação.
        #Assim teríamos: @ITEM=20000IDProjeto=INITMemcachedActiviti
        linha.append('@ITEM='+ str(df2.columns.get_loc(col)*100)+ '=OUT' + col)
        
linha.append('@ITEM=-1=|')
dict_col.append(linha)
print(dict_col)

[['@CONVERTED_FROM_TEXT', '@ITEM=20000=INITMicrosoftAzureTableStorage', '@ITEM=2000=INMicrosoftAzureTableStorage', '@ITEM=2=MicrosoftAzureTableStorage', '@ITEM=200=OUTMicrosoftAzureTableStorage', '@ITEM=30000=INITMySQL_MariaDB', '@ITEM=3000=INMySQL_MariaDB', '@ITEM=3=MySQL_MariaDB', '@ITEM=300=OUTMySQL_MariaDB', '@ITEM=40000=INITHyperSQL', '@ITEM=4000=INHyperSQL', '@ITEM=4=HyperSQL', '@ITEM=400=OUTHyperSQL', '@ITEM=50000=INITMarkLogic', '@ITEM=5000=INMarkLogic', '@ITEM=5=MarkLogic', '@ITEM=500=OUTMarkLogic', '@ITEM=60000=INITMSSQLServer_MicrosoftAzureSQLDatabase', '@ITEM=6000=INMSSQLServer_MicrosoftAzureSQLDatabase', '@ITEM=6=MSSQLServer_MicrosoftAzureSQLDatabase', '@ITEM=600=OUTMSSQLServer_MicrosoftAzureSQLDatabase', '@ITEM=70000=INITFileMaker', '@ITEM=7000=INFileMaker', '@ITEM=7=FileMaker', '@ITEM=700=OUTFileMaker', '@ITEM=80000=INITSinglestore', '@ITEM=8000=INSinglestore', '@ITEM=8=Singlestore', '@ITEM=800=OUTSinglestore', '@ITEM=90000=INITRiak_KV', '@ITEM=9000=INRiak_KV', '@ITEM=9=Riak_KV', '@ITEM=900=OUTRiak_KV', '@ITEM=100000=INITRedis', '@ITEM=10000=INRedis', '@ITEM=10=Redis', '@ITEM=1000=OUTRedis', '@ITEM=110000=INITAerospike', '@ITEM=11000=INAerospike', '@ITEM=11=Aerospike', '@ITEM=1100=OUTAerospike', '@ITEM=120000=INITGoogleCloudDatastore', '@ITEM=12000=INGoogleCloudDatastore', '@ITEM=12=GoogleCloudDatastore', '@ITEM=1200=OUTGoogleCloudDatastore', '@ITEM=130000=INITNeo4j', '@ITEM=13000=INNeo4j', '@ITEM=13=Neo4j', '@ITEM=1300=OUTNeo4j', '@ITEM=140000=INITH2', '@ITEM=14000=INH2', '@ITEM=14=H2', '@ITEM=1400=OUTH2', '@ITEM=150000=INITHBase', '@ITEM=15000=INHBase', '@ITEM=15=HBase', '@ITEM=1500=OUTHBase', '@ITEM=160000=INITArangoDB', '@ITEM=16000=INArangoDB', '@ITEM=16=ArangoDB', '@ITEM=1600=OUTArangoDB', '@ITEM=170000=INITSapHana', '@ITEM=17000=INSapHana', '@ITEM=17=SapHana', '@ITEM=1700=OUTSapHana', '@ITEM=180000=INITOracle', '@ITEM=18000=INOracle', '@ITEM=18=Oracle', '@ITEM=1800=OUTOracle', '@ITEM=190000=INITDynamoDB', '@ITEM=19000=INDynamoDB', '@ITEM=19=DynamoDB', '@ITEM=1900=OUTDynamoDB', '@ITEM=200000=INITFirebird', '@ITEM=20000=INFirebird', '@ITEM=20=Firebird', '@ITEM=2000=OUTFirebird', '@ITEM=210000=INITInformix', '@ITEM=21000=INInformix', '@ITEM=21=Informix', '@ITEM=2100=OUTInformix', '@ITEM=220000=INITIngres', '@ITEM=22000=INIngres', '@ITEM=22=Ingres', '@ITEM=2200=OUTIngres', '@ITEM=230000=INITIBM_DB2', '@ITEM=23000=INIBM_DB2', '@ITEM=23=IBM_DB2', '@ITEM=2300=OUTIBM_DB2', '@ITEM=240000=INITCouchbase', '@ITEM=24000=INCouchbase', '@ITEM=24=Couchbase', '@ITEM=2400=OUTCouchbase', '@ITEM=250000=INITGoogleCloudFilestore', '@ITEM=25000=INGoogleCloudFilestore', '@ITEM=25=GoogleCloudFilestore', '@ITEM=2500=OUTGoogleCloudFilestore', '@ITEM=260000=INITKdb', '@ITEM=26000=INKdb', '@ITEM=26=Kdb', '@ITEM=2600=OUTKdb', '@ITEM=270000=INITInterbase', '@ITEM=27000=INInterbase', '@ITEM=27=Interbase', '@ITEM=2700=OUTInterbase', '@ITEM=280000=INITFirebaseRealtime', '@ITEM=28000=INFirebaseRealtime', '@ITEM=28=FirebaseRealtime', '@ITEM=2800=OUTFirebaseRealtime', '@ITEM=290000=INITMongoDB', '@ITEM=29000=INMongoDB', '@ITEM=29=MongoDB', '@ITEM=2900=OUTMongoDB', '@ITEM=300000=INITHazelcast', '@ITEM=30000=INHazelcast', '@ITEM=30=Hazelcast', '@ITEM=3000=OUTHazelcast', '@ITEM=310000=INITImpala', '@ITEM=31000=INImpala', '@ITEM=31=Impala', '@ITEM=3100=OUTImpala', '@ITEM=320000=INITInflux_DB', '@ITEM=32000=INInflux_DB', '@ITEM=32=Influx_DB', '@ITEM=3200=OUTInflux_DB', '@ITEM=330000=INITSQLite', '@ITEM=33000=INSQLite', '@ITEM=33=SQLite', '@ITEM=3300=OUTSQLite', '@ITEM=340000=INITSnowflake', '@ITEM=34000=INSnowflake', '@ITEM=34=Snowflake', '@ITEM=3400=OUTSnowflake', '@ITEM=350000=INITRealm', '@ITEM=35000=INRealm', '@ITEM=35=Realm', '@ITEM=3500=OUTRealm', '@ITEM=360000=INITCassandra', '@ITEM=36000=INCassandra', '@ITEM=36=Cassandra', '@ITEM=3600=OUTCassandra', '@ITEM=370000=INITSAPSQLAnywhere', '@ITEM=37000=INSAPSQLAnywhere', '@ITEM=37=SAPSQLAnywhere', '@ITEM=3700=OUTSAPSQLAnywhere', '@ITEM=380000=INITMicrosoftAzureCosmosDB', '@ITEM=38000=INMicrosoftAzureCosmosDB', '@ITEM=38=MicrosoftAzureCosmosDB', '@ITEM=3800=OUTMicrosoftAzureCosmosDB', '@ITEM=390000=INITMS_Access', '@ITEM=39000=INMS_Access', '@ITEM=39=MS_Access', '@ITEM=3900=OUTMS_Access', '@ITEM=400000=INITSAPAdaptiveServer', '@ITEM=40000=INSAPAdaptiveServer', '@ITEM=40=SAPAdaptiveServer', '@ITEM=4000=OUTSAPAdaptiveServer', '@ITEM=410000=INITCouchDB', '@ITEM=41000=INCouchDB', '@ITEM=41=CouchDB', '@ITEM=4100=OUTCouchDB', '@ITEM=420000=INITClickHouse', '@ITEM=42000=INClickHouse', '@ITEM=42=ClickHouse', '@ITEM=4200=OUTClickHouse', '@ITEM=430000=INITVertica', '@ITEM=43000=INVertica', '@ITEM=43=Vertica', '@ITEM=4300=OUTVertica', '@ITEM=440000=INITTeradata', '@ITEM=44000=INTeradata', '@ITEM=44=Teradata', '@ITEM=4400=OUTTeradata', '@ITEM=450000=INITPostgreSQL_CockroachDB', '@ITEM=45000=INPostgreSQL_CockroachDB', '@ITEM=45=PostgreSQL_CockroachDB', '@ITEM=4500=OUTPostgreSQL_CockroachDB', '@ITEM=460000=INITPostGIS', '@ITEM=46000=INPostGIS', '@ITEM=46=PostGIS', '@ITEM=4600=OUTPostGIS', '@ITEM=470000=INITEtcd', '@ITEM=47000=INEtcd', '@ITEM=47=Etcd', '@ITEM=4700=OUTEtcd', '@ITEM=480000=INITJoin_Ignite_Sql', '@ITEM=48000=INJoin_Ignite_Sql', '@ITEM=48=Join_Ignite_Sql', '@ITEM=4800=OUTJoin_Ignite_Sql', '@ITEM=490000=INITJoin_Ignite_NoSql', '@ITEM=49000=INJoin_Ignite_NoSql', '@ITEM=49=Join_Ignite_NoSql', '@ITEM=4900=OUTJoin_Ignite_NoSql', '@ITEM=500000=INITJoin_Virtuoso_Sql', '@ITEM=50000=INJoin_Virtuoso_Sql', '@ITEM=50=Join_Virtuoso_Sql', '@ITEM=5000=OUTJoin_Virtuoso_Sql', '@ITEM=510000=INITJoin_Virtuoso_NoSql', '@ITEM=51000=INJoin_Virtuoso_NoSql', '@ITEM=51=Join_Virtuoso_NoSql', '@ITEM=5100=OUTJoin_Virtuoso_NoSql', '@ITEM=-1=|']]

In [8]:
# Function to check if the DBMS exists
def verify_BD (db, list):
    try:
        BD = list.index(db)
    except:
        BD = -1
    return BD

In [9]:
#Function to divide the lists
def separate_list(list):
    list1=[]
    list2=[]
    start = 0
    limit_pos =[]
    final = len(list)
    #print(final)
    
    for i,l in enumerate (list):
        if l == '-1':
            limit_pos.append(i)
        #print(limit_pos)
        
    # list = lista.reverse
    # print (list)
    if final > 0 and len(limit_pos) > 0:
        for j,p in enumerate (limit_pos[::-1]): #[::-1]
            if len(limit_pos) == 1 and final > p:
                 list1 = list[:p]
                 list2 = list[p+1:]
            elif len(limit_pos) <= 2 and (list[final-1] == '-1' or list[final-1] == '-1 -2') :
                start = limit_pos[j-2]
                list1 = list[start+1:p]
                if list[final-1] == '-1 -2':
                    list2 = list[p+1:j-1]  
                else:                     
                    list2 = list[p+1:]           
                #print('entrou no 1',  j, p, start, j-1, j-2)
                break#return list1,list2   
            else:
                start = limit_pos[j-2]
                list1 = list[start+1:p]  
                if list[final-1] == '-1 -2':
                    #print('entrou no 1 do else', j, p, start, j-1, list[67], final)
                    list2 = list[p+1:j-1]
                else: 
                    #print('entrou no 2', j, p, start, j-1, list[67], final)                    
                    list2 = list[p+1:]
                #print('entrou no 2', j, p, start, j-1, list[67], final)
                break
    else:
        list1 = ['-1']
        #list1 = list.copy()
        list2 = list.copy()
    return list1 , list2
linha = [6000,3000,40,50,'-1']
#'-1', 6, 8, 32, 36, 49000, '-1',6, 8, 32, 36, 49, 50000, 6, 8, 32, 36, 49, 50000, '-1', 6, 8, 32, 36, 4900, 5000, '-1', 6, 8, 32, 36, 49000, '-1', 6, 8, 32, 36, 4900, '-1', 6, 8, 32, 36, 4900, 50000, '-1', 6, 8, 32, 36, 49000, '-1', 6, 8, 32, 36, 4900, '-1', 6, 8, 32, 36, 5400, '-1 -2'] 
print(separate_list(linha))
line1,line2 = separate_list(linha)
print(line1)
print(line2)

([6000, 3000, 40, 50], [])
[6000, 3000, 40, 50]
[]

Iteration to generate the categorical data to be used in the sequential patterns algorithm
Adjusts to considering only INIT without IN on first version, but only DB that starting in first version

In [10]:
coluna=[]

proj = 0
projant = 'xxxx'
#commitant = 0
linha=[]
linhaproj=[]
linhaant = []
contproj = 0
#noBD = -2
#noBDant = -2
for row in df2.itertuples():
    #print(row.Index) 
    #print((col)
    commitant = 0
    for col in df2.columns:
        if col == "PROJECTS":
            #proj = proj + 1
            #linha.append(getattr(row, col))
            #print(getattr(row, col))
            projatual = getattr(row, col)
            #print('atual novo:', projatual, 'anterior:', projant)
            
        elif col == "COMMITS":
            commitatual = getattr(row, col)
            #commitant = commitatual
            #linha.append(getattr(row, col))
            #print('Commit:',getattr(row, col))
        # Only enter if it is traversing the lines7of the same project or if it is the first line of the dataframe
        elif projatual == projant or row.Index == 0:# projant == 'xxxx':
            # Only enter if you are in the same version
            if (commitatual == commitant) :
                #If the value of column(BD) == 1, then this DB exists
                if (getattr(row, col) == 1):
                    line1 = []
                    line2 = []           
                    #Split the list into two lists        
                    line1,line2 = separate_list(linha)
                    #Only enter if the first list is not null and if the second list is greater than the first
                    if len(line1)!= 0 and len(line2) > len(line1):# >=
                        #initBD =  verify_BD(df2.columns.get_loc(col)*10000,line2)
                        inBD = verify_BD(df2.columns.get_loc(col)*1000,line2)
                        BD = verify_BD(df2.columns.get_loc(col),line2)
                        outBD= verify_BD(df2.columns.get_loc(col)*100,line2)
                        #If there is no DB in the second list, check the first list
                        if inBD < 0 and BD < 0 and outBD < 0:
                            inBD = verify_BD(df2.columns.get_loc(col)*1000,line1)
                            BD = verify_BD(df2.columns.get_loc(col),line1)
                            outBD= verify_BD(df2.columns.get_loc(col)*100,line1)
                    else:
                        #So list 1 is bigger than list 2, look for the DB in the first list
                        #initBD =  verify_BD(df2.columns.get_loc(col)*10000,line1)
                        inBD = verify_BD(df2.columns.get_loc(col)*1000,line1)
                        BD = verify_BD(df2.columns.get_loc(col),line1)
                        outBD= verify_BD(df2.columns.get_loc(col)*100,line1)

                    #Inserts the DB entry since it doesn't exist in any of the lists or left one of them
                    if (outBD >=0) or (BD < 0 and inBD < 0):
                        if commitatual == 1: # or (commitatual != 1 and '-1' not in linha): #INIT in first version #1
                            #print(commitatual,commitant, "entrou1")
                            linha.append(df2.columns.get_loc(col)*10000)
                            print(commitatual,commitant,"entrou 1 if",linha)
                        else:#if (df2.columns.get_loc(col) not in linha):         
                            linha.append(df2.columns.get_loc(col)*1000) #IN  including DB for correct count when generating sequential pattern
                            print(commitatual,commitant,"entrou 1 else",linha)
                        linha.append(df2.columns.get_loc(col))    
                        linhaant.append(df2.columns.get_loc(col)*1000)
                        linhaant.append(df2.columns.get_loc(col))
                        print(commitatual,commitant,"total 1",linha)
                    else:
                        #Insert the permanence of the DB
                        #linha.append('No'+col)
                        #linha.append(-df2.columns.get_loc(col))
                        linha.append(df2.columns.get_loc(col))
                        linhaant.append(df2.columns.get_loc(col))     
                    commitant = commitatual
                #If the value of column(BD) == 0, then this DB does not exist.  
                elif getattr(row, col) == 0:
                    #If it is the first column and the lineant had DB
                    if len(linha) == 0 and len(linhaant) != 0:
                        #Check the existence of the DB in the entire list
                        #initBD =  verify_BD(df2.columns.get_loc(col)*10000,linha)
                        inBD = verify_BD(df2.columns.get_loc(col)*1000, linha)
                        BD = verify_BD(df2.columns.get_loc(col), linha)
                        outBD =  verify_BD(df2.columns.get_loc(col)*100, linha)
                        # If the DB exists on the line, then insert the output
                        if BD >= 0 or (inBD >= 0 and BD >= 0 and outBD < 0): # Added BD>=0 with inBD to correct init split
                            linha.append(df2.columns.get_loc(col)*100)
                            linhaant.append(df2.columns.get_loc(col)*100)
                            print(commitatual,commitant,"entrou 1 elif 1",df2.columns.get_loc(col)*100,linha)
                        commitant = commitatual
                    elif len(linha) != 0 and len(linhaant) != 0:  
                        line1 = []
                        line2 = []  
                        #Split the list into two lists                
                        line1,line2 = separate_list(linha)
                        #Only enter if the first list is not null and if the second list is greater than the first
                        if len(line1)!= 0 and len(line2) > len(line1):# >=
                            inBD = verify_BD(df2.columns.get_loc(col)*1000,line2)
                            BD = verify_BD(df2.columns.get_loc(col),line2)
                            outBD= verify_BD(df2.columns.get_loc(col)*100,line2)
                            #If there is no DB in the second list, check the first list
                            if inBD < 0 and BD < 0 and outBD < 0:
                                inBD = verify_BD(df2.columns.get_loc(col)*1000,line1)
                                BD = verify_BD(df2.columns.get_loc(col),line1)
                                outBD= verify_BD(df2.columns.get_loc(col)*100,line1)
                        else:
                            #So list 1 is bigger than list 2, look for the DB in the first list
                            inBD = verify_BD(df2.columns.get_loc(col)*1000,line1)
                            BD = verify_BD(df2.columns.get_loc(col),line1)
                            outBD= verify_BD(df2.columns.get_loc(col)*100,line1)    

                        #Inserts the BD output since it exists in one of the lists
                        if BD >= 0 or (inBD >= 0 and BD >= 0 and outBD < 0): #Added BD>=0 with inBD to correct init split
                            linha.append(df2.columns.get_loc(col)*100)
                            linhaant.append(df2.columns.get_loc(col)*100)
                            print(commitatual,commitant,"entrou 1 elif 2",df2.columns.get_loc(col),linha, BD, inBD, outBD)
                        commitant = commitatual   
            # Only enter if it is in a different version from the previous one (different versions)        
            elif (commitatual != commitant):
                #If the value of column(BD) == 1, then this DB exists
                if getattr(row, col) == 1:
                    #Only enter if it is on the first line of the dataframe or if the list is empty
                    if row.Index == 0 or len(linha) == 0:
                        #Check the existence of the DB in the entire list
                        inBD = verify_BD(df2.columns.get_loc(col)*1000,linha)
                        outBD= verify_BD(df2.columns.get_loc(col)*100,linha)
                        
                        # If the DB does not exist on the line, then insert the entry
                        if inBD < 0 or outBD >=0:
                            if commitatual == 1:  # or (commitatual != 1 and '-1' not in linha): #INIT in first version#len(linha)== 0: #2
                                #print(commitatual,commitant, "entrou 2")
                                linhaproj.append(projatual)
                                linha.append(df2.columns.get_loc(col)*10000)
                                #print(commitatual,commitant,"entrou 2 if",linha)
                            else:  
                                linha.append(df2.columns.get_loc(col)*1000) #IN other versions #incluindo o BD para contagem correta ao gerar o padrão sequencial)
                            linha.append(df2.columns.get_loc(col))      #including DB for correct count when generating sequential pattern)
                            linhaant.append(df2.columns.get_loc(col)*1000)
                            linhaant.append(df2.columns.get_loc(col))
                            #print(commitatual,commitant,"total 2 if",linha)
                        else: 
                            # Else insert the permanence of the DB
                            linha.append(df2.columns.get_loc(col))
                            linhaant.append(df2.columns.get_loc(col))
                    #Enter the other lines or the list is not empty  
                    else:
                        line1 = []
                        line2 = []   
                        #Split the list into two lists                
                        line1,line2 = separate_list(linha)
                        diff = []
                        #New version
                        linha.append('-1')
                        linhaant.append('-1')
                        #linhaant.append(col)
                        #linhaant.append(df2.columns.get_loc(col))
                        
                        #Only enter if the first list is not null and if the second list is greater than or equal to the first
                        if len(line1)!= 0 and len(line2) >= len(line1):# >= this signal was included to resolve situation 12 on line1 and 1200 on line2
                            inBD = verify_BD(df2.columns.get_loc(col)*1000,line2)
                            BD = verify_BD(df2.columns.get_loc(col),line2)
                            outBD= verify_BD(df2.columns.get_loc(col)*100,line2)
                            #If there is no DB in the second list, check the first list
                            if inBD < 0 and BD < 0 and outBD < 0:
                                inBD = verify_BD(df2.columns.get_loc(col)*1000,line1)
                                BD = verify_BD(df2.columns.get_loc(col),line1)
                                outBD= verify_BD(df2.columns.get_loc(col)*100,line1)
                        else:
                            #So list 1 is bigger than list 2, look for the DB in the first list 
                            inBD = verify_BD(df2.columns.get_loc(col)*1000,line1)
                            BD = verify_BD(df2.columns.get_loc(col),line1)
                            outBD= verify_BD(df2.columns.get_loc(col)*100,line1)
                            #If in list 1 the DB left or if there was no DB, check the second list
                            if (inBD >= 0 or BD >= 0 or outBD >= 0) or (inBD < 0 and BD < 0 and outBD < 0): #Included to force you to look at the latest version, you may need to compare BDline1 with BDline2
                                inBD = verify_BD(df2.columns.get_loc(col)*1000,line2)
                                BD = verify_BD(df2.columns.get_loc(col),line2)
                                outBD= verify_BD(df2.columns.get_loc(col)*100,line2)        
                                                                                  
                        # If DB exited or does not exist, then insert entry    
                        if outBD >=0 or (BD < 0 and inBD < 0):
                            if commitatual == 1: # or (commitatual != 1 and '-1' not in linha): #INIT in first version#len(linha) == 0:#3
                                #print(commitatual,commitant,"entrou 3")
                                linha.append(df2.columns.get_loc(col)*10000)
                                #print(commitatual,commitant,"entrou 3 if",linha)
                            else:   
                                linha.append(df2.columns.get_loc(col)*1000)#IN other versions #including DB for correct count when generating sequential pattern)
                                #print(commitatual,commitant,"entrou 3 else",linha)
                            linha.append(df2.columns.get_loc(col))      
                            linhaant.append(df2.columns.get_loc(col)*1000)
                            linhaant.append(df2.columns.get_loc(col))
                            #print(commitatual,commitant,"entrou 3 total",linha)
                        else:
                            #Else insert the permanence of the DB
                            linha.append(df2.columns.get_loc(col))
                            linhaant.append(df2.columns.get_loc(col))                        
                    commitant = commitatual
                
                #If the value of column(DB) == 0, then this DB does not exist.
                elif getattr(row, col) == 0: 
                    list1 = []
                    list2 = []
                    newList = [] 
                    newList2 = []
                    #if len(linha)>0 and type(linha[0]) == str:
                        #linhaproj.append(linha[0])
                        #print("__________________________________________________")
                        #print("ListaProj")
                        #print(linhaproj)
                        #print("__________________________________________________")
                        #print("Lista")
                        #linha.pop(0)
                        #print(linha) 
                    #Split the list into two lists 
                    list1,list2 = separate_list(linha) 
                    # Only enter if list1 or line is not empty
                    if len(list1) != 0 and len(linha) != 0: #and list1 != '-1' 
                        delim ='-1'
                        #Only enter if you don't have the value "-1" in any of the lists
                        if delim not in list1 and delim not in list2:
                            #Insert the value if it is in list1 and not in list2
                            newList = [int (l) for l in list1 if l not in list2 ]
                            #If newList is not empty
                            if len(newList) != 0:
                                # Cycling through the values ​​of newList
                                for i,n in enumerate (newList):
                                    #If the value is a multiple of 1000 and is not in list1, that is,
                                    #if DB entry and permanence do not exist in list1
                                    if  n % 1000 == 0 and (n not in list1) and (int(n/1000) not in list1):
                                        #Insert value in newList
                                        newList[i] = int (n/1000)
                                    #If the value is a multiple of 100, that is, if it is an output
                                    elif n % 100 == 0:
                                        #Insert value in newList
                                        newList[i] = int(n/100) 
                                #Multiply by 100 the values ​​that do not refer to DB entries      
                                newList = [int (i) *100 if i %1000 != 0 else int(i/1000) for i in newList ]
                        #If newList is still populated       
                        if len(newList) != 0:# or len(newList2) != 0 : #
                            #Inserts the value in newList2, the value of newList if it is in list1 and not in list2
                            newList2 = [int (l) for l in newList if (int(l/100) in list1 and l not in list2)]
                            #Calculate position to insert
                            pos = len(linha)-len(newList2) 
                            #linha.insert(pos,newList2)
                            #Cycling through the values ​​of newList2
                            for i,l in enumerate (newList2):
                                #If it is the first value and the position does not have "-1"
                                if i == 0 and linha[pos] != '-1':    #or linha[pos] != -1
                                    #Inserts the DB output at position
                                    linha.insert(pos,l)
                                    linhaant.insert(pos,l)
                                    print(commitatual, commitant, 'entrou  if diferença', df2.columns.get_loc(col), linha)
                                else:
                                    #Else insert the DB output in the next position
                                    linha.insert(pos+1,l) 
                                    linhaant.insert(pos+1,l)
                                    print(commitatual, commitant, 'entrou else diferença', df2.columns.get_loc(col), linha)
                        #If one of the two newLists is empty and list2 is not empty, that is,
                        #if no differences were found between split and scrolled lists from left to right
                        if (len(newList) == 0 or len(newList2) == 0) and len(list2) != 0:
                            #If the value of column(BD) == 0, then this DB does not exist.
                            if getattr(row, col) == 0:
                                inBD = verify_BD(df2.columns.get_loc(col)*1000,list2)
                                BD = verify_BD(df2.columns.get_loc(col),list2)
                                outBD= verify_BD(df2.columns.get_loc(col)*100,list2)
                                #Insert the DB output already if it exists in list2
                                if BD >= 0 and outBD < 0: 
                                    linha.append('-1')
                                    linhaant.append('-1')
                                    linha.append(df2.columns.get_loc(col)*100)
                                    linhaant.append(df2.columns.get_loc(col)*100)   
                                    print(commitatual, commitant, 'entrou newlist', df2.columns.get_loc(col), linha)                                       
                                    commitant = commitatual
        #Different projects, i.e. project of the new line is different from the project of the previous line
        elif projatual != projant:
            #If the value of column(BD) == 1, then this DB exists
            if getattr(row, col) == 1:# and commitatual == 10:
                #Finish the line with all versions of the project
                linha.append('-1 -2')
                linhaproj.append(projatual)
                #linhaant.append(linha)
                coluna.append(linha)
                linha=[]
                linhaant=[]
                #Inserts the DB entry that exists in the column
                #print("Versão1",projatual,commitatual)
                #linha.append(df2.columns.get_loc(col)+1000)
                #print(len(linha),projatual,commitatual)
                if commitatual == 1: #or (commitatual != 1 and '-1' not in linha): #INIT in first version#len(linha)== 0: #4
                    #print(commitatual,commitant, "entrou 4")
                    #linha.append(projatual)
                    linha.append(df2.columns.get_loc(col)*10000)
                    print(commitatual,commitant, "entrou 4 if",linha)
                else:   
                    linha.append(df2.columns.get_loc(col)*1000)# IN other versions
                    print(commitatual,commitant, "entrou 4 else",linha)
                linha.append(df2.columns.get_loc(col))
                #print("Versão1",projatual,commitatual,linha)
                #linhaant.append(df2.columns.get_loc(col)+1000)
                linhaant.append(df2.columns.get_loc(col)*1000)
                linhaant.append(df2.columns.get_loc(col))  
                print(commitatual,commitant, "total 4",linha)            
                #contproj = contproj + 1
                projant = projatual
                commitant = commitatual
             #Enter if the value of column(BD) == 0, that is, BD does not exist and the versions are different
            elif getattr(row, col) == 0 and (commitatual != commitant):
                #If the line is filled
                if len(linha) != 0:
                    diff=[]
                    #count_versions=[]
                    #Check versions
                    #for i,l in enumerate (linha):
                            #if l == '-1':
                               #count_versions.append(i)
                    #Split the list into two lists
                    line1,line2 = separate_list(linha)
                    #If list 2 is filled
                    if len(line2) != 0:
                            #Returns the difference between the lists
                            diff = list(set(line1).difference(line2))
                            #Calculate the position to insert the difference
                            pos = len(linha)-1
                            #Check if the DB or DB entry does not exist in list 1
                            diff2 = [int (l) for l in diff if l not in line1 and l/1000 not in line1]  #Check again as it may bring up an inBD. ex: 28000                                                                          
                            #If diff2 is not empty
                            if len(diff2) != 0:
                                #Insert in diff2 the value that is in diff, but not in list2
                                diff2 = [int (l) for l in diff if l and l/1000 not in line2]
                            else:
                                 #Insert into diff2 the value that is in diff2, but not in list2
                                diff2 = [int (l) for l in diff2 if l and l/1000 not in line2]

                            #Cycling through the values ​​of diff2
                            for i,l in enumerate (diff2):
                                #If it is the first value and the position does not have "-1"
                                if i == 0 and linha[pos] != '-1':    #or linha[pos] != -1
                                    #Inserts the DB difference in the position
                                    linha.insert(pos,l)
                                    linhaant.insert(pos,l)
                                else:
                                    #Else insert the DB difference in the next position
                                    linha.insert(pos+1,l) 
                                    linhaant.insert(pos+1,l)  
                    #Finish the line with all versions of the project                                     
                    linha.append('-1 -2')
                    linhaproj.append(projatual)
                    #linhaant.append(col)
                    coluna.append(linha)
                    linha=[]
                    linhaant=[]
                projant = projatual
                commitant = commitatual
            #Enter if the value of column(BD) == 0, that is, BD does not exist and is in the same version
            #elif getattr(row, col) == 0 and (commitatual == commitant):
             #   print("Entrou", linha)
              #  if len(linha) != 0:
               #     #linha.append('-1 -2')
                #    #linhaant.append(col)
                 #   #coluna.append(linha)
                  #  #linha=[]
                   # linhaant=[]
                #projant = projatual
                #commitant = commitatual
            contproj = contproj + 1
        #projant=projatual
        #commitant = 0
    projant = projatual 
    #If it is on the last line of the dataframe
    if row.Index == len(df2) - 1:
        diff=[]
        #Split the list into two lists
        line1,line2 = separate_list(linha)
        #If list 2 is filled
        if len(line2) != 0:
            #Returns the difference between the lists
            diff = list(set(line1).difference(line2))
            #Calculate the position to insert the difference
            pos = len(linha)-len(diff)
            #Check if the DB or DB entry does not exist in list 1 
            diff2 = [int (l) for l in diff if l not in line1 and l/1000 not in line1]#Check again as it may bring up an inBD. ex: 28000
            #If diff2 is not empty
            if len(diff2) != 0:
                #Insert in diff2 the value that is in diff, but not in list2
                diff2 = [int (l) for l in diff if l and l/1000 not in line2]
            else:
                #Insert into diff2 the value that is in diff2, but not in list2
                diff2 = [int (l) for l in diff2 if l and l/1000 not in line2]

            #Cycling through the values ​​of diff2
            for i,l in enumerate (diff2):
                #If it is the first value and the position does not have "-1"
                if i == 0 and linha[pos] != '-1':    #or linha[pos] != -1
                    #Inserts the DB output at position
                    linha.insert(pos,l*100)
                    linhaant.insert(pos,l*100)
                    #print(commitatual, commitant, 'entrou ultimo if', df2.columns.get_loc(col), linha)
                else:
                    #Inserts the DB output in the next position
                    linha.insert(pos+1,l*100) 
                    linhaant.insert(pos+1,l*100)
                    #print(commitatual, commitant, 'entrou ultimo else', df2.columns.get_loc(col), linha)
        #Finish the line with all versions of the project
        linha.append('-1 -2')
        linhaproj.append(projatual)
        coluna.append(linha)
        contproj = contproj + 1
print(len(linha))
#print(len(linhaant),linhaant)
#print(len(linha))
#print(contproj)
#print(coluna)
#print(linhaproj)

with open(SEQ_PATTERNS_DIR + os.sep + 'sequencial_project.txt', "w") as output:
    output.write(str(linhaproj))

1 1 entrou 1 if [30000, 3, 140000]
1 1 total 1 [30000, 3, 140000, 14]
1 1 entrou 1 if [30000, 3, 140000, 14, 180000]
1 1 total 1 [30000, 3, 140000, 14, 180000, 18]
1 1 entrou 1 if [30000, 3, 140000, 14, 180000, 18, 450000]
1 1 total 1 [30000, 3, 140000, 14, 180000, 18, 450000, 45]
2 2 entrou 1 else [30000, 3, 140000, 14, 180000, 18, 450000, 45, '-1', 3, 14, 18, 23000]
2 2 total 1 [30000, 3, 140000, 14, 180000, 18, 450000, 45, '-1', 3, 14, 18, 23000, 23]
2 2 entrou 1 else [30000, 3, 140000, 14, 180000, 18, 450000, 45, '-1', 3, 14, 18, 23000, 23, 37000]
2 2 total 1 [30000, 3, 140000, 14, 180000, 18, 450000, 45, '-1', 3, 14, 18, 23000, 23, 37000, 37]
2 2 entrou 1 else [30000, 3, 140000, 14, 180000, 18, 450000, 45, '-1', 3, 14, 18, 23000, 23, 37000, 37, 40000]
2 2 total 1 [30000, 3, 140000, 14, 180000, 18, 450000, 45, '-1', 3, 14, 18, 23000, 23, 37000, 37, 40000, 40]
3 3 entrou 1 else [30000, 3, 140000, 14, 180000, 18, 450000, 45, '-1', 3, 14, 18, 23000, 23, 37000, 37, 40000, 40, 45, '-1', 3, 6000]
3 3 total 1 [30000, 3, 140000, 14, 180000, 18, 450000, 45, '-1', 3, 14, 18, 23000, 23, 37000, 37, 40000, 40, 45, '-1', 3, 6000, 6]
5 5 entrou 1 else [30000, 3, 140000, 14, 180000, 18, 450000, 45, '-1', 3, 14, 18, 23000, 23, 37000, 37, 40000, 40, 45, '-1', 3, 6000, 6, 14, 18, 23, 37, 40, 45, '-1', 3, 6, 14, 18, 23, 37, 40, 45, '-1', 3, 4000]
5 5 total 1 [30000, 3, 140000, 14, 180000, 18, 450000, 45, '-1', 3, 14, 18, 23000, 23, 37000, 37, 40000, 40, 45, '-1', 3, 6000, 6, 14, 18, 23, 37, 40, 45, '-1', 3, 6, 14, 18, 23, 37, 40, 45, '-1', 3, 4000, 4]
5 5 entrou 1 else [30000, 3, 140000, 14, 180000, 18, 450000, 45, '-1', 3, 14, 18, 23000, 23, 37000, 37, 40000, 40, 45, '-1', 3, 6000, 6, 14, 18, 23, 37, 40, 45, '-1', 3, 6, 14, 18, 23, 37, 40, 45, '-1', 3, 4000, 4, 6, 14, 18, 23, 30000]
5 5 total 1 [30000, 3, 140000, 14, 180000, 18, 450000, 45, '-1', 3, 14, 18, 23000, 23, 37000, 37, 40000, 40, 45, '-1', 3, 6000, 6, 14, 18, 23, 37, 40, 45, '-1', 3, 6, 14, 18, 23, 37, 40, 45, '-1', 3, 4000, 4, 6, 14, 18, 23, 30000, 30]
5 5 entrou 1 else [30000, 3, 140000, 14, 180000, 18, 450000, 45, '-1', 3, 14, 18, 23000, 23, 37000, 37, 40000, 40, 45, '-1', 3, 6000, 6, 14, 18, 23, 37, 40, 45, '-1', 3, 6, 14, 18, 23, 37, 40, 45, '-1', 3, 4000, 4, 6, 14, 18, 23, 30000, 30, 37, 40000]
5 5 total 1 [30000, 3, 140000, 14, 180000, 18, 450000, 45, '-1', 3, 14, 18, 23000, 23, 37000, 37, 40000, 40, 45, '-1', 3, 6000, 6, 14, 18, 23, 37, 40, 45, '-1', 3, 6, 14, 18, 23, 37, 40, 45, '-1', 3, 4000, 4, 6, 14, 18, 23, 30000, 30, 37, 40000, 40]
6 6 entrou 1 elif 2 30 [30000, 3, 140000, 14, 180000, 18, 450000, 45, '-1', 3, 14, 18, 23000, 23, 37000, 37, 40000, 40, 45, '-1', 3, 6000, 6, 14, 18, 23, 37, 40, 45, '-1', 3, 6, 14, 18, 23, 37, 40, 45, '-1', 3, 4000, 4, 6, 14, 18, 23, 30000, 30, 37, 40000, 40, 45, '-1', 3, 4, 6, 14, 18, 23, 3000] 8 7 -1
6 6 entrou 1 else [30000, 3, 140000, 14, 180000, 18, 450000, 45, '-1', 3, 14, 18, 23000, 23, 37000, 37, 40000, 40, 45, '-1', 3, 6000, 6, 14, 18, 23, 37, 40, 45, '-1', 3, 6, 14, 18, 23, 37, 40, 45, '-1', 3, 4000, 4, 6, 14, 18, 23, 30000, 30, 37, 40000, 40, 45, '-1', 3, 4, 6, 14, 18, 23, 3000, 37, 40000]
6 6 total 1 [30000, 3, 140000, 14, 180000, 18, 450000, 45, '-1', 3, 14, 18, 23000, 23, 37000, 37, 40000, 40, 45, '-1', 3, 6000, 6, 14, 18, 23, 37, 40, 45, '-1', 3, 6, 14, 18, 23, 37, 40, 45, '-1', 3, 4000, 4, 6, 14, 18, 23, 30000, 30, 37, 40000, 40, 45, '-1', 3, 4, 6, 14, 18, 23, 3000, 37, 40000, 40]
7 0 entrou  if diferença 2 [30000, 3, 140000, 14, 180000, 18, 450000, 45, '-1', 3, 14, 18, 23000, 23, 37000, 37, 40000, 40, 45, '-1', 3, 6000, 6, 14, 18, 23, 37, 40, 45, '-1', 3, 6, 14, 18, 23, 37, 40, 45, '-1', 3, 4000, 4, 6, 14, 18, 23, 30000, 30, 37, 40000, 40, 45, '-1', 3, 4, 6, 14, 18, 23, 3000, 37, 40000, 40, 4000, 45]
7 0 entrou newlist 3 [30000, 3, 140000, 14, 180000, 18, 450000, 45, '-1', 3, 14, 18, 23000, 23, 37000, 37, 40000, 40, 45, '-1', 3, 6000, 6, 14, 18, 23, 37, 40, 45, '-1', 3, 6, 14, 18, 23, 37, 40, 45, '-1', 3, 4000, 4, 6, 14, 18, 23, 30000, 30, 37, 40000, 40, 45, '-1', 3, 4, 6, 14, 18, 23, 3000, 37, 40000, 40, 4000, 45, '-1', 300]
7 7 entrou 1 elif 2 4 [30000, 3, 140000, 14, 180000, 18, 450000, 45, '-1', 3, 14, 18, 23000, 23, 37000, 37, 40000, 40, 45, '-1', 3, 6000, 6, 14, 18, 23, 37, 40, 45, '-1', 3, 6, 14, 18, 23, 37, 40, 45, '-1', 3, 4000, 4, 6, 14, 18, 23, 30000, 30, 37, 40000, 40, 45, '-1', 3, 4, 6, 14, 18, 23, 3000, 37, 40000, 40, 4000, 45, '-1', 300, 400] 1 10 -1
7 7 entrou 1 elif 2 6 [30000, 3, 140000, 14, 180000, 18, 450000, 45, '-1', 3, 14, 18, 23000, 23, 37000, 37, 40000, 40, 45, '-1', 3, 6000, 6, 14, 18, 23, 37, 40, 45, '-1', 3, 6, 14, 18, 23, 37, 40, 45, '-1', 3, 4000, 4, 6, 14, 18, 23, 30000, 30, 37, 40000, 40, 45, '-1', 3, 4, 6, 14, 18, 23, 3000, 37, 40000, 40, 4000, 45, '-1', 300, 400, 600] 2 -1 -1
7 7 entrou 1 elif 2 14 [30000, 3, 140000, 14, 180000, 18, 450000, 45, '-1', 3, 14, 18, 23000, 23, 37000, 37, 40000, 40, 45, '-1', 3, 6000, 6, 14, 18, 23, 37, 40, 45, '-1', 3, 6, 14, 18, 23, 37, 40, 45, '-1', 3, 4000, 4, 6, 14, 18, 23, 30000, 30, 37, 40000, 40, 45, '-1', 3, 4, 6, 14, 18, 23, 3000, 37, 40000, 40, 4000, 45, '-1', 300, 400, 600, 1400] 3 -1 -1
7 7 entrou 1 elif 2 18 [30000, 3, 140000, 14, 180000, 18, 450000, 45, '-1', 3, 14, 18, 23000, 23, 37000, 37, 40000, 40, 45, '-1', 3, 6000, 6, 14, 18, 23, 37, 40, 45, '-1', 3, 6, 14, 18, 23, 37, 40, 45, '-1', 3, 4000, 4, 6, 14, 18, 23, 30000, 30, 37, 40000, 40, 45, '-1', 3, 4, 6, 14, 18, 23, 3000, 37, 40000, 40, 4000, 45, '-1', 300, 400, 600, 1400, 1800] 4 -1 -1
7 7 entrou 1 elif 2 23 [30000, 3, 140000, 14, 180000, 18, 450000, 45, '-1', 3, 14, 18, 23000, 23, 37000, 37, 40000, 40, 45, '-1', 3, 6000, 6, 14, 18, 23, 37, 40, 45, '-1', 3, 6, 14, 18, 23, 37, 40, 45, '-1', 3, 4000, 4, 6, 14, 18, 23, 30000, 30, 37, 40000, 40, 45, '-1', 3, 4, 6, 14, 18, 23, 3000, 37, 40000, 40, 4000, 45, '-1', 300, 400, 600, 1400, 1800, 2300] 5 -1 -1
7 7 entrou 1 elif 2 37 [30000, 3, 140000, 14, 180000, 18, 450000, 45, '-1', 3, 14, 18, 23000, 23, 37000, 37, 40000, 40, 45, '-1', 3, 6000, 6, 14, 18, 23, 37, 40, 45, '-1', 3, 6, 14, 18, 23, 37, 40, 45, '-1', 3, 4000, 4, 6, 14, 18, 23, 30000, 30, 37, 40000, 40, 45, '-1', 3, 4, 6, 14, 18, 23, 3000, 37, 40000, 40, 4000, 45, '-1', 300, 400, 600, 1400, 1800, 2300, 3700] 7 -1 -1
7 7 entrou 1 elif 2 40 [30000, 3, 140000, 14, 180000, 18, 450000, 45, '-1', 3, 14, 18, 23000, 23, 37000, 37, 40000, 40, 45, '-1', 3, 6000, 6, 14, 18, 23, 37, 40, 45, '-1', 3, 6, 14, 18, 23, 37, 40, 45, '-1', 3, 4000, 4, 6, 14, 18, 23, 30000, 30, 37, 40000, 40, 45, '-1', 3, 4, 6, 14, 18, 23, 3000, 37, 40000, 40, 4000, 45, '-1', 300, 400, 600, 1400, 1800, 2300, 3700, 4000] 9 8 10
7 7 entrou 1 elif 2 45 [30000, 3, 140000, 14, 180000, 18, 450000, 45, '-1', 3, 14, 18, 23000, 23, 37000, 37, 40000, 40, 45, '-1', 3, 6000, 6, 14, 18, 23, 37, 40, 45, '-1', 3, 6, 14, 18, 23, 37, 40, 45, '-1', 3, 4000, 4, 6, 14, 18, 23, 30000, 30, 37, 40000, 40, 45, '-1', 3, 4, 6, 14, 18, 23, 3000, 37, 40000, 40, 4000, 45, '-1', 300, 400, 600, 1400, 1800, 2300, 3700, 4000, 4500] 11 -1 -1
10 10 entrou 1 else [30000, 3, 140000, 14, 180000, 18, 450000, 45, '-1', 3, 14, 18, 23000, 23, 37000, 37, 40000, 40, 45, '-1', 3, 6000, 6, 14, 18, 23, 37, 40, 45, '-1', 3, 6, 14, 18, 23, 37, 40, 45, '-1', 3, 4000, 4, 6, 14, 18, 23, 30000, 30, 37, 40000, 40, 45, '-1', 3, 4, 6, 14, 18, 23, 3000, 37, 40000, 40, 4000, 45, '-1', 300, 400, 600, 1400, 1800, 2300, 3700, 4000, 4500, '-1', 14000, 14, '-1', 14, '-1', 14, 45000]
10 10 total 1 [30000, 3, 140000, 14, 180000, 18, 450000, 45, '-1', 3, 14, 18, 23000, 23, 37000, 37, 40000, 40, 45, '-1', 3, 6000, 6, 14, 18, 23, 37, 40, 45, '-1', 3, 6, 14, 18, 23, 37, 40, 45, '-1', 3, 4000, 4, 6, 14, 18, 23, 30000, 30, 37, 40000, 40, 45, '-1', 3, 4, 6, 14, 18, 23, 3000, 37, 40000, 40, 4000, 45, '-1', 300, 400, 600, 1400, 1800, 2300, 3700, 4000, 4500, '-1', 14000, 14, '-1', 14, '-1', 14, 45000, 45]
1 1 entrou 1 if [30000]
1 1 total 1 [30000, 3]
1 1 entrou 1 if [30000, 3, 60000]
1 1 total 1 [30000, 3, 60000, 6]
1 1 entrou 1 if [30000, 3, 60000, 6, 100000]
1 1 total 1 [30000, 3, 60000, 6, 100000, 10]
1 1 entrou 1 if [30000, 3, 60000, 6, 100000, 10, 180000]
1 1 total 1 [30000, 3, 60000, 6, 100000, 10, 180000, 18]
1 1 entrou 1 if [30000, 3, 60000, 6, 100000, 10, 180000, 18, 230000]
1 1 total 1 [30000, 3, 60000, 6, 100000, 10, 180000, 18, 230000, 23]
1 1 entrou 1 if [30000, 3, 60000, 6, 100000, 10, 180000, 18, 230000, 23, 340000]
1 1 total 1 [30000, 3, 60000, 6, 100000, 10, 180000, 18, 230000, 23, 340000, 34]
1 1 entrou 1 if [30000, 3, 60000, 6, 100000, 10, 180000, 18, 230000, 23, 340000, 34, 420000]
1 1 total 1 [30000, 3, 60000, 6, 100000, 10, 180000, 18, 230000, 23, 340000, 34, 420000, 42]
1 1 entrou 1 if [30000, 3, 60000, 6, 100000, 10, 180000, 18, 230000, 23, 340000, 34, 420000, 42, 450000]
1 1 total 1 [30000, 3, 60000, 6, 100000, 10, 180000, 18, 230000, 23, 340000, 34, 420000, 42, 450000, 45]
2 2 entrou 1 else [30000, 3, 60000, 6, 100000, 10, 180000, 18, 230000, 23, 340000, 34, 420000, 42, 450000, 45, '-1', 2000, 2, 3, 6, 10, 18, 19000]
2 2 total 1 [30000, 3, 60000, 6, 100000, 10, 180000, 18, 230000, 23, 340000, 34, 420000, 42, 450000, 45, '-1', 2000, 2, 3, 6, 10, 18, 19000, 19]
2 2 entrou 1 else [30000, 3, 60000, 6, 100000, 10, 180000, 18, 230000, 23, 340000, 34, 420000, 42, 450000, 45, '-1', 2000, 2, 3, 6, 10, 18, 19000, 19, 23, 29000]
2 2 total 1 [30000, 3, 60000, 6, 100000, 10, 180000, 18, 230000, 23, 340000, 34, 420000, 42, 450000, 45, '-1', 2000, 2, 3, 6, 10, 18, 19000, 19, 23, 29000, 29]
2 2 entrou 1 else [30000, 3, 60000, 6, 100000, 10, 180000, 18, 230000, 23, 340000, 34, 420000, 42, 450000, 45, '-1', 2000, 2, 3, 6, 10, 18, 19000, 19, 23, 29000, 29, 34, 36000]
2 2 total 1 [30000, 3, 60000, 6, 100000, 10, 180000, 18, 230000, 23, 340000, 34, 420000, 42, 450000, 45, '-1', 2000, 2, 3, 6, 10, 18, 19000, 19, 23, 29000, 29, 34, 36000, 36]
4 4 entrou 1 else [30000, 3, 60000, 6, 100000, 10, 180000, 18, 230000, 23, 340000, 34, 420000, 42, 450000, 45, '-1', 2000, 2, 3, 6, 10, 18, 19000, 19, 23, 29000, 29, 34, 36000, 36, 42, 45, '-1', 2, 3, 6, 10, 18, 19, 23, 29, 34, 36, 42, 45, '-1', 2, 3, 6, 10, 12000]
4 4 total 1 [30000, 3, 60000, 6, 100000, 10, 180000, 18, 230000, 23, 340000, 34, 420000, 42, 450000, 45, '-1', 2000, 2, 3, 6, 10, 18, 19000, 19, 23, 29000, 29, 34, 36000, 36, 42, 45, '-1', 2, 3, 6, 10, 18, 19, 23, 29, 34, 36, 42, 45, '-1', 2, 3, 6, 10, 12000, 12]
4 4 entrou 1 else [30000, 3, 60000, 6, 100000, 10, 180000, 18, 230000, 23, 340000, 34, 420000, 42, 450000, 45, '-1', 2000, 2, 3, 6, 10, 18, 19000, 19, 23, 29000, 29, 34, 36000, 36, 42, 45, '-1', 2, 3, 6, 10, 18, 19, 23, 29, 34, 36, 42, 45, '-1', 2, 3, 6, 10, 12000, 12, 14000]
4 4 total 1 [30000, 3, 60000, 6, 100000, 10, 180000, 18, 230000, 23, 340000, 34, 420000, 42, 450000, 45, '-1', 2000, 2, 3, 6, 10, 18, 19000, 19, 23, 29000, 29, 34, 36000, 36, 42, 45, '-1', 2, 3, 6, 10, 18, 19, 23, 29, 34, 36, 42, 45, '-1', 2, 3, 6, 10, 12000, 12, 14000, 14]
5 5 entrou 1 elif 2 14 [30000, 3, 60000, 6, 100000, 10, 180000, 18, 230000, 23, 340000, 34, 420000, 42, 450000, 45, '-1', 2000, 2, 3, 6, 10, 18, 19000, 19, 23, 29000, 29, 34, 36000, 36, 42, 45, '-1', 2, 3, 6, 10, 18, 19, 23, 29, 34, 36, 42, 45, '-1', 2, 3, 6, 10, 12000, 12, 14000, 14, 18, 19, 23, 29, 34, 36, 42, 45, '-1', 2, 3, 6, 10, 12, 1400] 7 6 -1
5 5 entrou 1 else [30000, 3, 60000, 6, 100000, 10, 180000, 18, 230000, 23, 340000, 34, 420000, 42, 450000, 45, '-1', 2000, 2, 3, 6, 10, 18, 19000, 19, 23, 29000, 29, 34, 36000, 36, 42, 45, '-1', 2, 3, 6, 10, 18, 19, 23, 29, 34, 36, 42, 45, '-1', 2, 3, 6, 10, 12000, 12, 14000, 14, 18, 19, 23, 29, 34, 36, 42, 45, '-1', 2, 3, 6, 10, 12, 1400, 18, 19, 23, 28000]
5 5 total 1 [30000, 3, 60000, 6, 100000, 10, 180000, 18, 230000, 23, 340000, 34, 420000, 42, 450000, 45, '-1', 2000, 2, 3, 6, 10, 18, 19000, 19, 23, 29000, 29, 34, 36000, 36, 42, 45, '-1', 2, 3, 6, 10, 18, 19, 23, 29, 34, 36, 42, 45, '-1', 2, 3, 6, 10, 12000, 12, 14000, 14, 18, 19, 23, 29, 34, 36, 42, 45, '-1', 2, 3, 6, 10, 12, 1400, 18, 19, 23, 28000, 28]
5 5 entrou 1 else [30000, 3, 60000, 6, 100000, 10, 180000, 18, 230000, 23, 340000, 34, 420000, 42, 450000, 45, '-1', 2000, 2, 3, 6, 10, 18, 19000, 19, 23, 29000, 29, 34, 36000, 36, 42, 45, '-1', 2, 3, 6, 10, 18, 19, 23, 29, 34, 36, 42, 45, '-1', 2, 3, 6, 10, 12000, 12, 14000, 14, 18, 19, 23, 29, 34, 36, 42, 45, '-1', 2, 3, 6, 10, 12, 1400, 18, 19, 23, 28000, 28, 29, 34, 36, 42, 44000]
5 5 total 1 [30000, 3, 60000, 6, 100000, 10, 180000, 18, 230000, 23, 340000, 34, 420000, 42, 450000, 45, '-1', 2000, 2, 3, 6, 10, 18, 19000, 19, 23, 29000, 29, 34, 36000, 36, 42, 45, '-1', 2, 3, 6, 10, 18, 19, 23, 29, 34, 36, 42, 45, '-1', 2, 3, 6, 10, 12000, 12, 14000, 14, 18, 19, 23, 29, 34, 36, 42, 45, '-1', 2, 3, 6, 10, 12, 1400, 18, 19, 23, 28000, 28, 29, 34, 36, 42, 44000, 44]
6 6 entrou 1 else [30000, 3, 60000, 6, 100000, 10, 180000, 18, 230000, 23, 340000, 34, 420000, 42, 450000, 45, '-1', 2000, 2, 3, 6, 10, 18, 19000, 19, 23, 29000, 29, 34, 36000, 36, 42, 45, '-1', 2, 3, 6, 10, 18, 19, 23, 29, 34, 36, 42, 45, '-1', 2, 3, 6, 10, 12000, 12, 14000, 14, 18, 19, 23, 29, 34, 36, 42, 45, '-1', 2, 3, 6, 10, 12, 1400, 18, 19, 23, 28000, 28, 29, 34, 36, 42, 44000, 44, 45, '-1', 2, 3, 6, 10, 12, 18, 19, 23, 28, 29, 34, 36, 42, 43000]
6 6 total 1 [30000, 3, 60000, 6, 100000, 10, 180000, 18, 230000, 23, 340000, 34, 420000, 42, 450000, 45, '-1', 2000, 2, 3, 6, 10, 18, 19000, 19, 23, 29000, 29, 34, 36000, 36, 42, 45, '-1', 2, 3, 6, 10, 18, 19, 23, 29, 34, 36, 42, 45, '-1', 2, 3, 6, 10, 12000, 12, 14000, 14, 18, 19, 23, 29, 34, 36, 42, 45, '-1', 2, 3, 6, 10, 12, 1400, 18, 19, 23, 28000, 28, 29, 34, 36, 42, 44000, 44, 45, '-1', 2, 3, 6, 10, 12, 18, 19, 23, 28, 29, 34, 36, 42, 43000, 43]
8 8 entrou 1 elif 2 36 [30000, 3, 60000, 6, 100000, 10, 180000, 18, 230000, 23, 340000, 34, 420000, 42, 450000, 45, '-1', 2000, 2, 3, 6, 10, 18, 19000, 19, 23, 29000, 29, 34, 36000, 36, 42, 45, '-1', 2, 3, 6, 10, 18, 19, 23, 29, 34, 36, 42, 45, '-1', 2, 3, 6, 10, 12000, 12, 14000, 14, 18, 19, 23, 29, 34, 36, 42, 45, '-1', 2, 3, 6, 10, 12, 1400, 18, 19, 23, 28000, 28, 29, 34, 36, 42, 44000, 44, 45, '-1', 2, 3, 6, 10, 12, 18, 19, 23, 28, 29, 34, 36, 42, 43000, 43, 44, 45, '-1', 2, 3, 6, 10, 12, 18, 19, 23, 28, 29, 34, 36, 42, 43, 44, 45, '-1', 2, 3, 6, 10, 12, 18, 19, 23, 28, 29, 34, 3600] 11 -1 -1
10 10 entrou 1 else [30000, 3, 60000, 6, 100000, 10, 180000, 18, 230000, 23, 340000, 34, 420000, 42, 450000, 45, '-1', 2000, 2, 3, 6, 10, 18, 19000, 19, 23, 29000, 29, 34, 36000, 36, 42, 45, '-1', 2, 3, 6, 10, 18, 19, 23, 29, 34, 36, 42, 45, '-1', 2, 3, 6, 10, 12000, 12, 14000, 14, 18, 19, 23, 29, 34, 36, 42, 45, '-1', 2, 3, 6, 10, 12, 1400, 18, 19, 23, 28000, 28, 29, 34, 36, 42, 44000, 44, 45, '-1', 2, 3, 6, 10, 12, 18, 19, 23, 28, 29, 34, 36, 42, 43000, 43, 44, 45, '-1', 2, 3, 6, 10, 12, 18, 19, 23, 28, 29, 34, 36, 42, 43, 44, 45, '-1', 2, 3, 6, 10, 12, 18, 19, 23, 28, 29, 34, 3600, 42, 43, 44, 45, '-1', 2, 3, 6, 10, 12, 18, 19, 23, 28, 29, 34, 42, 43, 44, 45, '-1', 2, 3, 6, 8000]
10 10 total 1 [30000, 3, 60000, 6, 100000, 10, 180000, 18, 230000, 23, 340000, 34, 420000, 42, 450000, 45, '-1', 2000, 2, 3, 6, 10, 18, 19000, 19, 23, 29000, 29, 34, 36000, 36, 42, 45, '-1', 2, 3, 6, 10, 18, 19, 23, 29, 34, 36, 42, 45, '-1', 2, 3, 6, 10, 12000, 12, 14000, 14, 18, 19, 23, 29, 34, 36, 42, 45, '-1', 2, 3, 6, 10, 12, 1400, 18, 19, 23, 28000, 28, 29, 34, 36, 42, 44000, 44, 45, '-1', 2, 3, 6, 10, 12, 18, 19, 23, 28, 29, 34, 36, 42, 43000, 43, 44, 45, '-1', 2, 3, 6, 10, 12, 18, 19, 23, 28, 29, 34, 36, 42, 43, 44, 45, '-1', 2, 3, 6, 10, 12, 18, 19, 23, 28, 29, 34, 3600, 42, 43, 44, 45, '-1', 2, 3, 6, 10, 12, 18, 19, 23, 28, 29, 34, 42, 43, 44, 45, '-1', 2, 3, 6, 8000, 8]
1 1 entrou 1 if [40000]
1 1 total 1 [40000, 4]
1 1 entrou 1 if [40000, 4, 180000]
1 1 total 1 [40000, 4, 180000, 18]
3 0 entrou newlist 3 [40000, 4, 180000, 18, '-1', 3000, 3, 4, 18, '-1', 300]
3 3 entrou 1 else [40000, 4, 180000, 18, '-1', 3000, 3, 4, 18, '-1', 300, 4, 18, 45000]
3 3 total 1 [40000, 4, 180000, 18, '-1', 3000, 3, 4, 18, '-1', 300, 4, 18, 45000, 45]
6 6 entrou 1 elif 2 18 [40000, 4, 180000, 18, '-1', 3000, 3, 4, 18, '-1', 300, 4, 18, 45000, 45, '-1', 3000, 3, 4, 18, 45, '-1', 3, 4, 18, 45, '-1', 3, 4, 1800] 2 -1 -1
10 10 entrou 1 else [3000, 3, '-1', 3, '-1', 3, '-1', 3, '-1', 3, '-1', 3, '-1', 3, '-1', 3, 10000]
10 10 total 1 [3000, 3, '-1', 3, '-1', 3, '-1', 3, '-1', 3, '-1', 3, '-1', 3, '-1', 3, 10000, 10]
1 1 entrou 1 if [30000]
1 1 total 1 [30000, 3]
10 10 entrou 1 else [30000, 3, '-1', 3, '-1', 3, '-1', 3, '-1', 3, '-1', 3, '-1', 3, '-1', 3, '-1', 3, '-1', 3, 18000]
10 10 total 1 [30000, 3, '-1', 3, '-1', 3, '-1', 3, '-1', 3, '-1', 3, '-1', 3, '-1', 3, '-1', 3, '-1', 3, 18000, 18]
7 0 entrou newlist 18 [18000, 18, '-1', 18, '-1', 1800]
1 1 entrou 1 if [100000]
1 1 total 1 [100000, 10]
3 0 entrou newlist 3 [100000, 10, '-1', 3000, 3, 10, '-1', 300]
4 4 entrou 1 else [100000, 10, '-1', 3000, 3, 10, '-1', 300, 10, '-1', 10, 47000]
4 4 total 1 [100000, 10, '-1', 3000, 3, 10, '-1', 300, 10, '-1', 10, 47000, 47]
10 10 entrou 1 elif 2 47 [100000, 10, '-1', 3000, 3, 10, '-1', 300, 10, '-1', 10, 47000, 47, '-1', 10, 47, '-1', 10, 47, '-1', 10, 47, '-1', 10, 47, '-1', 10, 47, '-1', 10, 4700] 1 -1 -1
1 1 entrou 1 if [30000]
1 1 total 1 [30000, 3]
1 1 entrou 1 if [30000, 3, 100000]
1 1 total 1 [30000, 3, 100000, 10]
1 1 entrou 1 if [30000, 3, 100000, 10, 150000]
1 1 total 1 [30000, 3, 100000, 10, 150000, 15]
1 1 entrou 1 if [30000, 3, 100000, 10, 150000, 15, 180000]
1 1 total 1 [30000, 3, 100000, 10, 150000, 15, 180000, 18]
2 2 entrou 1 else [30000, 3, 100000, 10, 150000, 15, 180000, 18, '-1', 3, 10, 14000]
2 2 total 1 [30000, 3, 100000, 10, 150000, 15, 180000, 18, '-1', 3, 10, 14000, 14]
2 2 entrou 1 elif 2 15 [30000, 3, 100000, 10, 150000, 15, 180000, 18, '-1', 3, 10, 14000, 14, 1500] 5 -1 -1
3 3 entrou 1 else [30000, 3, 100000, 10, 150000, 15, 180000, 18, '-1', 3, 10, 14000, 14, 1500, 18, '-1', 3, 10, 14, 18, 29000]
3 3 total 1 [30000, 3, 100000, 10, 150000, 15, 180000, 18, '-1', 3, 10, 14000, 14, 1500, 18, '-1', 3, 10, 14, 18, 29000, 29]
4 4 entrou 1 else [30000, 3, 100000, 10, 150000, 15, 180000, 18, '-1', 3, 10, 14000, 14, 1500, 18, '-1', 3, 10, 14, 18, 29000, 29, '-1', 3, 10, 14, 18, 29, 45000]
4 4 total 1 [30000, 3, 100000, 10, 150000, 15, 180000, 18, '-1', 3, 10, 14000, 14, 1500, 18, '-1', 3, 10, 14, 18, 29000, 29, '-1', 3, 10, 14, 18, 29, 45000, 45]
7 7 entrou 1 else [30000, 3, 100000, 10, 150000, 15, 180000, 18, '-1', 3, 10, 14000, 14, 1500, 18, '-1', 3, 10, 14, 18, 29000, 29, '-1', 3, 10, 14, 18, 29, 45000, 45, '-1', 3, 10, 14, 18, 29, 45, '-1', 3, 10, 14, 18, 29, 45, '-1', 3, 10, 14, 18, 29, 36000]
7 7 total 1 [30000, 3, 100000, 10, 150000, 15, 180000, 18, '-1', 3, 10, 14000, 14, 1500, 18, '-1', 3, 10, 14, 18, 29000, 29, '-1', 3, 10, 14, 18, 29, 45000, 45, '-1', 3, 10, 14, 18, 29, 45, '-1', 3, 10, 14, 18, 29, 45, '-1', 3, 10, 14, 18, 29, 36000, 36]
8 8 entrou 1 else [30000, 3, 100000, 10, 150000, 15, 180000, 18, '-1', 3, 10, 14000, 14, 1500, 18, '-1', 3, 10, 14, 18, 29000, 29, '-1', 3, 10, 14, 18, 29, 45000, 45, '-1', 3, 10, 14, 18, 29, 45, '-1', 3, 10, 14, 18, 29, 45, '-1', 3, 10, 14, 18, 29, 36000, 36, 45, '-1', 3, 6000]
8 8 total 1 [30000, 3, 100000, 10, 150000, 15, 180000, 18, '-1', 3, 10, 14000, 14, 1500, 18, '-1', 3, 10, 14, 18, 29000, 29, '-1', 3, 10, 14, 18, 29, 45000, 45, '-1', 3, 10, 14, 18, 29, 45, '-1', 3, 10, 14, 18, 29, 45, '-1', 3, 10, 14, 18, 29, 36000, 36, 45, '-1', 3, 6000, 6]
8 8 entrou 1 else [30000, 3, 100000, 10, 150000, 15, 180000, 18, '-1', 3, 10, 14000, 14, 1500, 18, '-1', 3, 10, 14, 18, 29000, 29, '-1', 3, 10, 14, 18, 29, 45000, 45, '-1', 3, 10, 14, 18, 29, 45, '-1', 3, 10, 14, 18, 29, 45, '-1', 3, 10, 14, 18, 29, 36000, 36, 45, '-1', 3, 6000, 6, 10, 14, 15000]

In [11]:
#df2.to_excel("input_sequencial_init_in_out.txt",index=True)
#file = open('input_sequencial_init_in_out_2.txt', "w")
#file = open( SEQ_PATTERNS_DIR + os.sep + 'testes/input_sequencial_init_in_out_3.txt', "w")
file = open( SEQ_PATTERNS_DIR + os.sep + 'input_sequencial_init_in_out.txt', "w") #'testes/input_sequencial_init_in_out_6.txt', "w")
#dict_col
dict = []
#file = open("input_sequencial_nb_neg.txt", "w")
specialChars = "[',']" # Para retirar estes caracteres que são incluídos pelo array
#for dict in dict_col: # Writes to file
 #   for specialChar in specialChars:
dict = str(dict_col).replace("[['",'')
dict = str(dict).replace("']]",'\n')
file.write(str(dict).replace("', '",'\n'))
#coluna.insert(0,str(dict_col))
for values in coluna: # Writes to file
    for specialChar in specialChars:
        values = str(values).replace(specialChar,'')
    file.write(str(values) + '\n')
file.close()

Now we have the input file in the format required by the SPMF library. To generate sequential patterns according to our analysis, via the command line, as follows the steps below:: in a folder containing spmf.jar and the output file output__in_out.txt, in this case in /resources/seq_patterns. 

a) To generate results in size 1:

 Run "java -jar spmf.jar run PrefixSpan input_sequencial_init_in_out.txt output_tam1.txt 1% 1" 

b) To generate results in size 3:

Run "java -jar spmf.jar run PrefixSpan input_sequencial_init_in_out.txt output_tam3.txt 1% 3" 

c) To generate results in size 4:

Run "java -jar spmf.jar run PrefixSpan input_sequencial_init_in_out.txt output_tam4_sid.txt 1% 4" 

d) Save the three output files in the resources/seq_pattens folder as they will be used by "historical_seqpatterns_filters.ipynb" script.

 
PrefixSpan is one of the fastest sequential pattern mining algorithm (http://www.philippe-fournier-viger.com/spmf/PrefixSpan.php). 
The PrefixSpan implementation allows to specify additional optional parameter(s) : 

    "maximum pattern length" allows to specify the maximum number of items that patterns found should contain. 

    "show sequences ids?" (true/false) This parameter allows to specify that sequence ids of sequences containing a pattern should be output for each pattern found.
     For example, if the parameter is set to true, each pattern in the output file will be followed by the keyword #SID followed by a list of sequences ids (integers separated by space). 
     For example, a line terminated by "#SID: 0 2" means that the pattern on this line appears in the first and the third sequences of the sequence database (sequences with ids 0 and 2). 
     Run "java -jar spmf.jar run PrefixSpan input_sequencial_init_in_out.txt output_tam4_sid.txt 1% 4 true"